	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

	.align 2
Cry_Bulbasaur::
	.incbin "sound/direct_sound_samples/cries/bulbasaur.bin"

	.align 2
Cry_Ivysaur::
	.incbin "sound/direct_sound_samples/cries/ivysaur.bin"

	.align 2
Cry_Venusaur::
	.incbin "sound/direct_sound_samples/cries/venusaur.bin"

	.align 2
Cry_Charmander::
	.incbin "sound/direct_sound_samples/cries/charmander.bin"

	.align 2
Cry_Charmeleon::
	.incbin "sound/direct_sound_samples/cries/charmeleon.bin"

	.align 2
Cry_Charizard::
	.incbin "sound/direct_sound_samples/cries/charizard.bin"

	.align 2
Cry_Squirtle::
	.incbin "sound/direct_sound_samples/cries/squirtle.bin"

	.align 2
Cry_Wartortle::
	.incbin "sound/direct_sound_samples/cries/wartortle.bin"

	.align 2
Cry_Blastoise::
	.incbin "sound/direct_sound_samples/cries/blastoise.bin"

	.align 2
Cry_Caterpie::
	.incbin "sound/direct_sound_samples/cries/caterpie.bin"

	.align 2
Cry_Metapod::
	.incbin "sound/direct_sound_samples/cries/metapod.bin"

	.align 2
Cry_Butterfree::
	.incbin "sound/direct_sound_samples/cries/butterfree.bin"

	.align 2
Cry_Weedle::
	.incbin "sound/direct_sound_samples/cries/weedle.bin"

	.align 2
Cry_Kakuna::
	.incbin "sound/direct_sound_samples/cries/kakuna.bin"

	.align 2
Cry_Beedrill::
	.incbin "sound/direct_sound_samples/cries/beedrill.bin"

	.align 2
Cry_Pidgey::
	.incbin "sound/direct_sound_samples/cries/pidgey.bin"

	.align 2
Cry_Pidgeotto::
	.incbin "sound/direct_sound_samples/cries/pidgeotto.bin"

	.align 2
Cry_Pidgeot::
	.incbin "sound/direct_sound_samples/cries/pidgeot.bin"

	.align 2
Cry_Rattata::
	.incbin "sound/direct_sound_samples/cries/rattata.bin"

	.align 2
Cry_Raticate::
	.incbin "sound/direct_sound_samples/cries/raticate.bin"

	.align 2
Cry_Spearow::
	.incbin "sound/direct_sound_samples/cries/spearow.bin"

	.align 2
Cry_Fearow::
	.incbin "sound/direct_sound_samples/cries/fearow.bin"

	.align 2
Cry_Ekans::
	.incbin "sound/direct_sound_samples/cries/ekans.bin"

	.align 2
Cry_Arbok::
	.incbin "sound/direct_sound_samples/cries/arbok.bin"

	.align 2
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cries/pikachu.bin"

	.align 2
Cry_Raichu::
	.incbin "sound/direct_sound_samples/cries/raichu.bin"

	.align 2
Cry_Sandshrew::
	.incbin "sound/direct_sound_samples/cries/sandshrew.bin"

	.align 2
Cry_Sandslash::
	.incbin "sound/direct_sound_samples/cries/sandslash.bin"

	.align 2
Cry_NidoranF::
	.incbin "sound/direct_sound_samples/cries/nidoran_f.bin"

	.align 2
Cry_Nidorina::
	.incbin "sound/direct_sound_samples/cries/nidorina.bin"

	.align 2
Cry_Nidoqueen::
	.incbin "sound/direct_sound_samples/cries/nidoqueen.bin"

	.align 2
Cry_NidoranM::
	.incbin "sound/direct_sound_samples/cries/nidoran_m.bin"

	.align 2
Cry_Nidorino::
	.incbin "sound/direct_sound_samples/cries/nidorino.bin"

	.align 2
Cry_Nidoking::
	.incbin "sound/direct_sound_samples/cries/nidoking.bin"

	.align 2
Cry_Clefairy::
	.incbin "sound/direct_sound_samples/cries/clefairy.bin"

	.align 2
Cry_Clefable::
	.incbin "sound/direct_sound_samples/cries/clefable.bin"

	.align 2
Cry_Vulpix::
	.incbin "sound/direct_sound_samples/cries/vulpix.bin"

	.align 2
Cry_Ninetales::
	.incbin "sound/direct_sound_samples/cries/ninetales.bin"

	.align 2
Cry_Jigglypuff::
	.incbin "sound/direct_sound_samples/cries/jigglypuff.bin"

	.align 2
Cry_Wigglytuff::
	.incbin "sound/direct_sound_samples/cries/wigglytuff.bin"

	.align 2
Cry_Zubat::
	.incbin "sound/direct_sound_samples/cries/zubat.bin"

	.align 2
Cry_Golbat::
	.incbin "sound/direct_sound_samples/cries/golbat.bin"

	.align 2
Cry_Oddish::
	.incbin "sound/direct_sound_samples/cries/oddish.bin"

	.align 2
Cry_Gloom::
	.incbin "sound/direct_sound_samples/cries/gloom.bin"

	.align 2
Cry_Vileplume::
	.incbin "sound/direct_sound_samples/cries/vileplume.bin"

	.align 2
Cry_Paras::
	.incbin "sound/direct_sound_samples/cries/paras.bin"

	.align 2
Cry_Parasect::
	.incbin "sound/direct_sound_samples/cries/parasect.bin"

	.align 2
Cry_Venonat::
	.incbin "sound/direct_sound_samples/cries/venonat.bin"

	.align 2
Cry_Venomoth::
	.incbin "sound/direct_sound_samples/cries/venomoth.bin"

	.align 2
Cry_Diglett::
	.incbin "sound/direct_sound_samples/cries/diglett.bin"

	.align 2
Cry_Dugtrio::
	.incbin "sound/direct_sound_samples/cries/dugtrio.bin"

	.align 2
Cry_Meowth::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Persian::
	.incbin "sound/direct_sound_samples/cries/persian.bin"

	.align 2
Cry_Psyduck::
	.incbin "sound/direct_sound_samples/cries/psyduck.bin"

	.align 2
Cry_Golduck::
	.incbin "sound/direct_sound_samples/cries/golduck.bin"

	.align 2
Cry_Mankey::
	.incbin "sound/direct_sound_samples/cries/mankey.bin"

	.align 2
Cry_Primeape::
	.incbin "sound/direct_sound_samples/cries/primeape.bin"

	.align 2
Cry_Growlithe::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Arcanine::
	.incbin "sound/direct_sound_samples/cries/arcanine.bin"

	.align 2
Cry_Poliwag::
	.incbin "sound/direct_sound_samples/cries/poliwag.bin"

	.align 2
Cry_Poliwhirl::
	.incbin "sound/direct_sound_samples/cries/poliwhirl.bin"

	.align 2
Cry_Poliwrath::
	.incbin "sound/direct_sound_samples/cries/poliwrath.bin"

	.align 2
Cry_Abra::
	.incbin "sound/direct_sound_samples/cries/abra.bin"

	.align 2
Cry_Kadabra::
	.incbin "sound/direct_sound_samples/cries/kadabra.bin"

	.align 2
Cry_Alakazam::
	.incbin "sound/direct_sound_samples/cries/alakazam.bin"

	.align 2
Cry_Machop::
	.incbin "sound/direct_sound_samples/cries/machop.bin"

	.align 2
Cry_Machoke::
	.incbin "sound/direct_sound_samples/cries/machoke.bin"

	.align 2
Cry_Machamp::
	.incbin "sound/direct_sound_samples/cries/machamp.bin"

	.align 2
Cry_Bellsprout::
	.incbin "sound/direct_sound_samples/cries/bellsprout.bin"

	.align 2
Cry_Weepinbell::
	.incbin "sound/direct_sound_samples/cries/weepinbell.bin"

	.align 2
Cry_Victreebel::
	.incbin "sound/direct_sound_samples/cries/victreebel.bin"

	.align 2
Cry_Tentacool::
	.incbin "sound/direct_sound_samples/cries/tentacool.bin"

	.align 2
Cry_Tentacruel::
	.incbin "sound/direct_sound_samples/cries/tentacruel.bin"

	.align 2
Cry_Geodude::
	.incbin "sound/direct_sound_samples/cries/geodude.bin"

	.align 2
Cry_Graveler::
	.incbin "sound/direct_sound_samples/cries/graveler.bin"

	.align 2
Cry_Golem::
	.incbin "sound/direct_sound_samples/cries/golem.bin"

	.align 2
Cry_Ponyta::
	.incbin "sound/direct_sound_samples/cries/ponyta.bin"

	.align 2
Cry_Rapidash::
	.incbin "sound/direct_sound_samples/cries/rapidash.bin"

	.align 2
Cry_Slowpoke::
	.incbin "sound/direct_sound_samples/cries/slowpoke.bin"

	.align 2
Cry_Slowbro::
	.incbin "sound/direct_sound_samples/cries/slowbro.bin"

	.align 2
Cry_Magnemite::
	.incbin "sound/direct_sound_samples/cries/magnemite.bin"

	.align 2
Cry_Magneton::
	.incbin "sound/direct_sound_samples/cries/magneton.bin"

	.align 2
Cry_Farfetchd::
	.incbin "sound/direct_sound_samples/cries/farfetchd.bin"

	.align 2
Cry_Doduo::
	.incbin "sound/direct_sound_samples/cries/doduo.bin"

	.align 2
Cry_Dodrio::
	.incbin "sound/direct_sound_samples/cries/dodrio.bin"

	.align 2
Cry_Seel::
	.incbin "sound/direct_sound_samples/cries/seel.bin"

	.align 2
Cry_Dewgong::
	.incbin "sound/direct_sound_samples/cries/dewgong.bin"

	.align 2
Cry_Grimer::
	.incbin "sound/direct_sound_samples/cries/grimer.bin"

	.align 2
Cry_Muk::
	.incbin "sound/direct_sound_samples/cries/muk.bin"

	.align 2
Cry_Shellder::
	.incbin "sound/direct_sound_samples/cries/shellder.bin"

	.align 2
Cry_Cloyster::
	.incbin "sound/direct_sound_samples/cries/cloyster.bin"

	.align 2
Cry_Gastly::
	.incbin "sound/direct_sound_samples/cries/gastly.bin"

	.align 2
Cry_Haunter::
	.incbin "sound/direct_sound_samples/cries/haunter.bin"

	.align 2
Cry_Gengar::
	.incbin "sound/direct_sound_samples/cries/gengar.bin"

	.align 2
Cry_Onix::
	.incbin "sound/direct_sound_samples/cries/onix.bin"

	.align 2
Cry_Drowzee::
	.incbin "sound/direct_sound_samples/cries/drowzee.bin"

	.align 2
Cry_Hypno::
	.incbin "sound/direct_sound_samples/cries/hypno.bin"

	.align 2
Cry_Krabby::
	.incbin "sound/direct_sound_samples/cries/krabby.bin"

	.align 2
Cry_Kingler::
	.incbin "sound/direct_sound_samples/cries/kingler.bin"

	.align 2
Cry_Voltorb::
	.incbin "sound/direct_sound_samples/cries/voltorb.bin"

	.align 2
Cry_Electrode::
	.incbin "sound/direct_sound_samples/cries/electrode.bin"

	.align 2
Cry_Exeggcute::
	.incbin "sound/direct_sound_samples/cries/exeggcute.bin"

	.align 2
Cry_Exeggutor::
	.incbin "sound/direct_sound_samples/cries/exeggutor.bin"

	.align 2
Cry_Cubone::
	.incbin "sound/direct_sound_samples/cries/cubone.bin"

	.align 2
Cry_Marowak::
	.incbin "sound/direct_sound_samples/cries/marowak.bin"

	.align 2
Cry_Hitmonlee::
	.incbin "sound/direct_sound_samples/cries/hitmonlee.bin"

	.align 2
Cry_Hitmonchan::
	.incbin "sound/direct_sound_samples/cries/hitmonchan.bin"

	.align 2
Cry_Lickitung::
	.incbin "sound/direct_sound_samples/cries/lickitung.bin"

	.align 2
Cry_Koffing::
	.incbin "sound/direct_sound_samples/cries/koffing.bin"

	.align 2
Cry_Weezing::
	.incbin "sound/direct_sound_samples/cries/weezing.bin"

	.align 2
Cry_Rhyhorn::
	.incbin "sound/direct_sound_samples/cries/rhyhorn.bin"

	.align 2
Cry_Rhydon::
	.incbin "sound/direct_sound_samples/cries/rhydon.bin"

	.align 2
Cry_Chansey::
	.incbin "sound/direct_sound_samples/cries/chansey.bin"

	.align 2
Cry_Tangela::
	.incbin "sound/direct_sound_samples/cries/tangela.bin"

	.align 2
Cry_Kangaskhan::
	.incbin "sound/direct_sound_samples/cries/kangaskhan.bin"

	.align 2
Cry_Horsea::
	.incbin "sound/direct_sound_samples/cries/horsea.bin"

	.align 2
Cry_Seadra::
	.incbin "sound/direct_sound_samples/cries/seadra.bin"

	.align 2
Cry_Goldeen::
	.incbin "sound/direct_sound_samples/cries/goldeen.bin"

	.align 2
Cry_Seaking::
	.incbin "sound/direct_sound_samples/cries/seaking.bin"

	.align 2
Cry_Staryu::
	.incbin "sound/direct_sound_samples/cries/staryu.bin"

	.align 2
Cry_Starmie::
	.incbin "sound/direct_sound_samples/cries/starmie.bin"

	.align 2
Cry_MrMime::
	.incbin "sound/direct_sound_samples/cries/mr_mime.bin"

	.align 2
Cry_Scyther::
	.incbin "sound/direct_sound_samples/cries/scyther.bin"

	.align 2
Cry_Jynx::
	.incbin "sound/direct_sound_samples/cries/jynx.bin"

	.align 2
Cry_Electabuzz::
	.incbin "sound/direct_sound_samples/cries/electabuzz.bin"

	.align 2
Cry_Magmar::
	.incbin "sound/direct_sound_samples/cries/magmar.bin"

	.align 2
Cry_Pinsir::
	.incbin "sound/direct_sound_samples/cries/pinsir.bin"

	.align 2
Cry_Tauros::
	.incbin "sound/direct_sound_samples/cries/tauros.bin"

	.align 2
Cry_Magikarp::
	.incbin "sound/direct_sound_samples/cries/magikarp.bin"

	.align 2
Cry_Gyarados::
	.incbin "sound/direct_sound_samples/cries/gyarados.bin"

	.align 2
Cry_Lapras::
	.incbin "sound/direct_sound_samples/cries/lapras.bin"

	.align 2
Cry_Ditto::
	.incbin "sound/direct_sound_samples/cries/ditto.bin"

	.align 2
Cry_Eevee::
	.incbin "sound/direct_sound_samples/cries/eevee.bin"

	.align 2
Cry_Vaporeon::
	.incbin "sound/direct_sound_samples/cries/vaporeon.bin"

	.align 2
Cry_Jolteon::
	.incbin "sound/direct_sound_samples/cries/jolteon.bin"

	.align 2
Cry_Flareon::
	.incbin "sound/direct_sound_samples/cries/flareon.bin"

	.align 2
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cries/porygon.bin"

	.align 2
Cry_Omanyte::
	.incbin "sound/direct_sound_samples/cries/omanyte.bin"

	.align 2
Cry_Omastar::
	.incbin "sound/direct_sound_samples/cries/omastar.bin"

	.align 2
Cry_Kabuto::
	.incbin "sound/direct_sound_samples/cries/kabuto.bin"

	.align 2
Cry_Kabutops::
	.incbin "sound/direct_sound_samples/cries/kabutops.bin"

	.align 2
Cry_Aerodactyl::
	.incbin "sound/direct_sound_samples/cries/aerodactyl.bin"

	.align 2
Cry_Snorlax::
	.incbin "sound/direct_sound_samples/cries/snorlax.bin"

	.align 2
Cry_Articuno::
	.incbin "sound/direct_sound_samples/cries/articuno.bin"

	.align 2
Cry_Zapdos::
	.incbin "sound/direct_sound_samples/cries/zapdos.bin"

	.align 2
Cry_Moltres::
	.incbin "sound/direct_sound_samples/cries/moltres.bin"

	.align 2
Cry_Dratini::
	.incbin "sound/direct_sound_samples/cries/dratini.bin"

	.align 2
Cry_Dragonair::
	.incbin "sound/direct_sound_samples/cries/dragonair.bin"

	.align 2
Cry_Dragonite::
	.incbin "sound/direct_sound_samples/cries/dragonite.bin"

	.align 2
Cry_Mewtwo::
	.incbin "sound/direct_sound_samples/cries/mewtwo.bin"

	.align 2
Cry_Mew::
	.incbin "sound/direct_sound_samples/cries/mew.bin"

	.align 2
Cry_Chikorita::
	.incbin "sound/direct_sound_samples/cries/chikorita.bin"

	.align 2
Cry_Bayleef::
	.incbin "sound/direct_sound_samples/cries/bayleef.bin"

	.align 2
Cry_Meganium::
	.incbin "sound/direct_sound_samples/cries/meganium.bin"

	.align 2
Cry_Cyndaquil::
	.incbin "sound/direct_sound_samples/cries/cyndaquil.bin"

	.align 2
Cry_Quilava::
	.incbin "sound/direct_sound_samples/cries/quilava.bin"

	.align 2
Cry_Typhlosion::
	.incbin "sound/direct_sound_samples/cries/typhlosion.bin"

	.align 2
Cry_Totodile::
	.incbin "sound/direct_sound_samples/cries/totodile.bin"

	.align 2
Cry_Croconaw::
	.incbin "sound/direct_sound_samples/cries/croconaw.bin"

	.align 2
Cry_Feraligatr::
	.incbin "sound/direct_sound_samples/cries/feraligatr.bin"

	.align 2
Cry_Sentret::
	.incbin "sound/direct_sound_samples/cries/sentret.bin"

	.align 2
Cry_Furret::
	.incbin "sound/direct_sound_samples/cries/furret.bin"

	.align 2
Cry_Hoothoot::
	.incbin "sound/direct_sound_samples/cries/hoothoot.bin"

	.align 2
Cry_Noctowl::
	.incbin "sound/direct_sound_samples/cries/noctowl.bin"

	.align 2
Cry_Ledyba::
	.incbin "sound/direct_sound_samples/cries/ledyba.bin"

	.align 2
Cry_Ledian::
	.incbin "sound/direct_sound_samples/cries/ledian.bin"

	.align 2
Cry_Spinarak::
	.incbin "sound/direct_sound_samples/cries/spinarak.bin"

	.align 2
Cry_Ariados::
	.incbin "sound/direct_sound_samples/cries/ariados.bin"

	.align 2
Cry_Crobat::
	.incbin "sound/direct_sound_samples/cries/crobat.bin"

	.align 2
Cry_Chinchou::
	.incbin "sound/direct_sound_samples/cries/chinchou.bin"

	.align 2
Cry_Lanturn::
	.incbin "sound/direct_sound_samples/cries/lanturn.bin"

	.align 2
Cry_Pichu::
	.incbin "sound/direct_sound_samples/cries/pichu.bin"

	.align 2
Cry_Cleffa::
	.incbin "sound/direct_sound_samples/cries/cleffa.bin"

	.align 2
Cry_Igglybuff::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Togepi::
	.incbin "sound/direct_sound_samples/cries/togepi.bin"

	.align 2
Cry_Togetic::
	.incbin "sound/direct_sound_samples/cries/togetic.bin"

	.align 2
Cry_Natu::
	.incbin "sound/direct_sound_samples/cries/natu.bin"

	.align 2
Cry_Xatu::
	.incbin "sound/direct_sound_samples/cries/xatu.bin"

	.align 2
Cry_Mareep::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Flaaffy::
	.incbin "sound/direct_sound_samples/cries/flaaffy.bin"

	.align 2
Cry_Ampharos::
	.incbin "sound/direct_sound_samples/cries/ampharos.bin"

	.align 2
Cry_Bellossom::
	.incbin "sound/direct_sound_samples/cries/bellossom.bin"

	.align 2
Cry_Marill::
	.incbin "sound/direct_sound_samples/cries/marill.bin"

	.align 2
Cry_Azumarill::
	.incbin "sound/direct_sound_samples/cries/azumarill.bin"

	.align 2
Cry_Sudowoodo::
	.incbin "sound/direct_sound_samples/cries/sudowoodo.bin"

	.align 2
Cry_Politoed::
	.incbin "sound/direct_sound_samples/cries/politoed.bin"

	.align 2
Cry_Hoppip::
	.incbin "sound/direct_sound_samples/cries/hoppip.bin"

	.align 2
Cry_Skiploom::
	.incbin "sound/direct_sound_samples/cries/skiploom.bin"

	.align 2
Cry_Jumpluff::
	.incbin "sound/direct_sound_samples/cries/jumpluff.bin"

	.align 2
Cry_Aipom::
	.incbin "sound/direct_sound_samples/cries/aipom.bin"

	.align 2
Cry_Sunkern::
	.incbin "sound/direct_sound_samples/cries/sunkern.bin"

	.align 2
Cry_Sunflora::
	.incbin "sound/direct_sound_samples/cries/sunflora.bin"

	.align 2
Cry_Yanma::
	.incbin "sound/direct_sound_samples/cries/yanma.bin"

	.align 2
Cry_Wooper::
	.incbin "sound/direct_sound_samples/cries/wooper.bin"

	.align 2
Cry_Quagsire::
	.incbin "sound/direct_sound_samples/cries/quagsire.bin"

	.align 2
Cry_Espeon::
	.incbin "sound/direct_sound_samples/cries/espeon.bin"

	.align 2
Cry_Umbreon::
	.incbin "sound/direct_sound_samples/cries/umbreon.bin"

	.align 2
Cry_Murkrow::
	.incbin "sound/direct_sound_samples/cries/murkrow.bin"

	.align 2
Cry_Slowking::
	.incbin "sound/direct_sound_samples/cries/slowking.bin"

	.align 2
Cry_Misdreavus::
	.incbin "sound/direct_sound_samples/cries/misdreavus.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cries/unown.bin"

	.align 2
Cry_Wobbuffet::
	.incbin "sound/direct_sound_samples/cries/wobbuffet.bin"

	.align 2
Cry_Girafarig::
	.incbin "sound/direct_sound_samples/cries/girafarig.bin"

	.align 2
Cry_Pineco::
	.incbin "sound/direct_sound_samples/cries/pineco.bin"

	.align 2
Cry_Forretress::
	.incbin "sound/direct_sound_samples/cries/forretress.bin"

	.align 2
Cry_Dunsparce::
	.incbin "sound/direct_sound_samples/cries/dunsparce.bin"

	.align 2
Cry_Gligar::
	.incbin "sound/direct_sound_samples/cries/gligar.bin"

	.align 2
Cry_Steelix::
	.incbin "sound/direct_sound_samples/cries/steelix.bin"

	.align 2
Cry_Snubbull::
	.incbin "sound/direct_sound_samples/cries/snubbull.bin"

	.align 2
Cry_Granbull::
	.incbin "sound/direct_sound_samples/cries/granbull.bin"

	.align 2
Cry_Qwilfish::
	.incbin "sound/direct_sound_samples/cries/qwilfish.bin"

	.align 2
Cry_Scizor::
	.incbin "sound/direct_sound_samples/cries/scizor.bin"

	.align 2
Cry_Shuckle::
	.incbin "sound/direct_sound_samples/cries/shuckle.bin"

	.align 2
Cry_Heracross::
	.incbin "sound/direct_sound_samples/cries/heracross.bin"

	.align 2
Cry_Sneasel::
	.incbin "sound/direct_sound_samples/cries/sneasel.bin"

	.align 2
Cry_Teddiursa::
	.incbin "sound/direct_sound_samples/cries/teddiursa.bin"

	.align 2
Cry_Ursaring::
	.incbin "sound/direct_sound_samples/cries/ursaring.bin"

	.align 2
Cry_Slugma::
	.incbin "sound/direct_sound_samples/cries/slugma.bin"

	.align 2
Cry_Magcargo::
	.incbin "sound/direct_sound_samples/cries/magcargo.bin"

	.align 2
Cry_Swinub::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_Piloswine::
	.incbin "sound/direct_sound_samples/cries/piloswine.bin"

	.align 2
Cry_Corsola::
	.incbin "sound/direct_sound_samples/cries/corsola.bin"

	.align 2
Cry_Remoraid::
	.incbin "sound/direct_sound_samples/cries/remoraid.bin"

	.align 2
Cry_Octillery::
	.incbin "sound/direct_sound_samples/cries/octillery.bin"

	.align 2
Cry_Delibird::
	.incbin "sound/direct_sound_samples/cries/delibird.bin"

	.align 2
Cry_Mantine::
	.incbin "sound/direct_sound_samples/cries/mantine.bin"

	.align 2
Cry_Skarmory::
	.incbin "sound/direct_sound_samples/cries/skarmory.bin"

	.align 2
Cry_Houndour::
	.incbin "sound/direct_sound_samples/cries/houndour.bin"

	.align 2
Cry_Houndoom::
	.incbin "sound/direct_sound_samples/cries/houndoom.bin"

	.align 2
Cry_Kingdra::
	.incbin "sound/direct_sound_samples/cries/kingdra.bin"

	.align 2
Cry_Phanpy::
	.incbin "sound/direct_sound_samples/cries/phanpy.bin"

	.align 2
Cry_Donphan::
	.incbin "sound/direct_sound_samples/cries/donphan.bin"

	.align 2
Cry_Porygon2::
	.incbin "sound/direct_sound_samples/cries/porygon2.bin"

	.align 2
Cry_Stantler::
	.incbin "sound/direct_sound_samples/cries/stantler.bin"

	.align 2
Cry_Smeargle::
	.incbin "sound/direct_sound_samples/cries/smeargle.bin"

	.align 2
Cry_Tyrogue::
	.incbin "sound/direct_sound_samples/cries/tyrogue.bin"

	.align 2
Cry_Hitmontop::
	.incbin "sound/direct_sound_samples/cries/hitmontop.bin"

	.align 2
Cry_Smoochum::
	.incbin "sound/direct_sound_samples/cries/smoochum.bin"

	.align 2
Cry_Elekid::
	.incbin "sound/direct_sound_samples/cries/elekid.bin"

	.align 2
Cry_Magby::
	.incbin "sound/direct_sound_samples/cries/magby.bin"

	.align 2
Cry_Miltank::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Blissey::
	.incbin "sound/direct_sound_samples/cries/blissey.bin"

	.align 2
Cry_Raikou::
	.incbin "sound/direct_sound_samples/cries/raikou.bin"

	.align 2
Cry_Entei::
	.incbin "sound/direct_sound_samples/cries/entei.bin"

	.align 2
Cry_Suicune::
	.incbin "sound/direct_sound_samples/cries/suicune.bin"

	.align 2
Cry_Larvitar::
	.incbin "sound/direct_sound_samples/cries/larvitar.bin"

	.align 2
Cry_Pupitar::
	.incbin "sound/direct_sound_samples/cries/pupitar.bin"

	.align 2
Cry_Tyranitar::
	.incbin "sound/direct_sound_samples/cries/tyranitar.bin"

	.align 2
Cry_Lugia::
	.incbin "sound/direct_sound_samples/cries/lugia.bin"

	.align 2
Cry_HoOh::
	.incbin "sound/direct_sound_samples/cries/ho_oh.bin"

	.align 2
Cry_Celebi::
	.incbin "sound/direct_sound_samples/cries/celebi.bin"

	.align 2
Cry_Kecleon::
	.incbin "sound/direct_sound_samples/cries/kecleon.bin"

	.align 2
Cry_Roselia::
	.incbin "sound/direct_sound_samples/cries/roselia.bin"

	.align 2
Cry_Torkoal::
	.incbin "sound/direct_sound_samples/cries/torkoal.bin"

	.align 2
Cry_Electrike::
	.incbin "sound/direct_sound_samples/cries/electrike.bin"

	.align 2
Cry_Manectric::
	.incbin "sound/direct_sound_samples/cries/manectric.bin"

	.align 2
Cry_Duskull::
	.incbin "sound/direct_sound_samples/cries/duskull.bin"

	.align 2
Cry_Latias::
	.incbin "sound/direct_sound_samples/cries/latias.bin"

	.align 2
Cry_Wynaut::
	.incbin "sound/direct_sound_samples/cries/wynaut.bin"

	.align 2
Cry_Seviper::
	.incbin "sound/direct_sound_samples/cries/seviper.bin"

	.align 2
Cry_Sharpedo::
	.incbin "sound/direct_sound_samples/cries/sharpedo.bin"

	.align 2
Cry_Zangoose::
	.incbin "sound/direct_sound_samples/cries/zangoose.bin"

	.align 2
Cry_Azurill::
	.incbin "sound/direct_sound_samples/cries/azurill.bin"

	.align 2
Cry_Swablu::
	.incbin "sound/direct_sound_samples/cries/swablu.bin"

	.align 2
Cry_Altaria::
	.incbin "sound/direct_sound_samples/cries/altaria.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cries/unused_265.bin"

	.align 2
Cry_Taillow::
	.incbin "sound/direct_sound_samples/cries/taillow.bin"

	.align 2
Cry_Swellow::
	.incbin "sound/direct_sound_samples/cries/swellow.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cries/unused_268.bin"

	.align 2
Cry_Spinda::
	.incbin "sound/direct_sound_samples/cries/spinda.bin"

	.align 2
Cry_Torchic::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Combusken::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Blaziken::
	.incbin "sound/direct_sound_samples/cries/blaziken.bin"

	.align 2
Cry_Treecko::
	.incbin "sound/direct_sound_samples/cries/treecko.bin"

	.align 2
Cry_Grovyle::
	.incbin "sound/direct_sound_samples/cries/grovyle.bin"

	.align 2
Cry_Sceptile::
	.incbin "sound/direct_sound_samples/cries/sceptile.bin"

	.align 2
Cry_Mudkip::
	.incbin "sound/direct_sound_samples/cries/mudkip.bin"

	.align 2
Cry_Marshtomp::
	.incbin "sound/direct_sound_samples/cries/marshtomp.bin"

	.align 2
Cry_Swampert::
	.incbin "sound/direct_sound_samples/cries/swampert.bin"

	.align 2
Cry_Pelipper::
	.incbin "sound/direct_sound_samples/cries/pelipper.bin"

	.align 2
Cry_Wingull::
	.incbin "sound/direct_sound_samples/cries/wingull.bin"

	.align 2
Cry_Banette::
	.incbin "sound/direct_sound_samples/cries/banette.bin"

	.align 2
Cry_Shuppet::
	.incbin "sound/direct_sound_samples/cries/shuppet.bin"

	.align 2
Cry_Lotad::
	.incbin "sound/direct_sound_samples/cries/lotad.bin"

	.align 2
Cry_Lombre::
	.incbin "sound/direct_sound_samples/cries/lombre.bin"

	.align 2
Cry_Ludicolo::
	.incbin "sound/direct_sound_samples/cries/ludicolo.bin"

	.align 2
Cry_Seedot::
	.incbin "sound/direct_sound_samples/cries/seedot.bin"

	.align 2
Cry_Nuzleaf::
	.incbin "sound/direct_sound_samples/cries/nuzleaf.bin"

	.align 2
Cry_Shiftry::
	.incbin "sound/direct_sound_samples/cries/shiftry.bin"

	.align 2
Cry_Carvanha::
	.incbin "sound/direct_sound_samples/cries/carvanha.bin"

	.align 2
Cry_Wurmple::
	.incbin "sound/direct_sound_samples/cries/wurmple.bin"

	.align 2
Cry_Silcoon::
	.incbin "sound/direct_sound_samples/cries/silcoon.bin"

	.align 2
Cry_Beautifly::
	.incbin "sound/direct_sound_samples/cries/beautifly.bin"

	.align 2
Cry_Cascoon::
	.incbin "sound/direct_sound_samples/cries/cascoon.bin"

	.align 2
Cry_Dustox::
	.incbin "sound/direct_sound_samples/cries/dustox.bin"

	.align 2
Cry_Ralts::
	.incbin "sound/direct_sound_samples/cries/ralts.bin"

	.align 2
Cry_Kirlia::
	.incbin "sound/direct_sound_samples/cries/kirlia.bin"

	.align 2
Cry_Gardevoir::
	.incbin "sound/direct_sound_samples/cries/gardevoir.bin"

	.align 2
Cry_Slakoth::
	.incbin "sound/direct_sound_samples/cries/slakoth.bin"

	.align 2
Cry_Vigoroth::
	.incbin "sound/direct_sound_samples/cries/vigoroth.bin"

	.align 2
Cry_Slaking::
	.incbin "sound/direct_sound_samples/cries/slaking.bin"

	.align 2
Cry_Nincada::
	.incbin "sound/direct_sound_samples/cries/nincada.bin"

	.align 2
Cry_Ninjask::
	.incbin "sound/direct_sound_samples/cries/ninjask.bin"

	.align 2
Cry_Shedinja::
	.incbin "sound/direct_sound_samples/cries/shedinja.bin"

	.align 2
Cry_Makuhita::
	.incbin "sound/direct_sound_samples/cries/makuhita.bin"

	.align 2
Cry_Hariyama::
	.incbin "sound/direct_sound_samples/cries/hariyama.bin"

	.align 2
Cry_Nosepass::
	.incbin "sound/direct_sound_samples/cries/nosepass.bin"

	.align 2
Cry_Glalie::
	.incbin "sound/direct_sound_samples/cries/glalie.bin"

	.align 2
Cry_Plusle::
	.incbin "sound/direct_sound_samples/cries/plusle.bin"

	.align 2
Cry_Minun::
	.incbin "sound/direct_sound_samples/cries/minun.bin"

	.align 2
Cry_Surskit::
	.incbin "sound/direct_sound_samples/cries/surskit.bin"

	.align 2
Cry_Masquerain::
	.incbin "sound/direct_sound_samples/cries/masquerain.bin"

	.align 2
Cry_Skitty::
	.incbin "sound/direct_sound_samples/cries/skitty.bin"

	.align 2
Cry_Delcatty::
	.incbin "sound/direct_sound_samples/cries/delcatty.bin"

	.align 2
Cry_Gulpin::
	.incbin "sound/direct_sound_samples/cries/gulpin.bin"

	.align 2
Cry_Swalot::
	.incbin "sound/direct_sound_samples/cries/swalot.bin"

	.align 2
Cry_Numel::
	.incbin "sound/direct_sound_samples/cries/numel.bin"

	.align 2
Cry_Camerupt::
	.incbin "sound/direct_sound_samples/cries/camerupt.bin"

	.align 2
Cry_Barboach::
	.incbin "sound/direct_sound_samples/cries/barboach.bin"

	.align 2
Cry_Whiscash::
	.incbin "sound/direct_sound_samples/cries/whiscash.bin"

	.align 2
Cry_Corphish::
	.incbin "sound/direct_sound_samples/cries/corphish.bin"

	.align 2
Cry_Crawdaunt::
	.incbin "sound/direct_sound_samples/cries/crawdaunt.bin"

	.align 2
Cry_Spoink::
	.incbin "sound/direct_sound_samples/cries/spoink.bin"

	.align 2
Cry_Grumpig::
	.incbin "sound/direct_sound_samples/cries/grumpig.bin"

	.align 2
Cry_Trapinch::
	.incbin "sound/direct_sound_samples/cries/trapinch.bin"

	.align 2
Cry_Vibrava::
	.incbin "sound/direct_sound_samples/cries/vibrava.bin"

	.align 2
Cry_Flygon::
	.incbin "sound/direct_sound_samples/cries/flygon.bin"

	.align 2
Cry_Cacnea::
	.incbin "sound/direct_sound_samples/cries/cacnea.bin"

	.align 2
Cry_Cacturne::
	.incbin "sound/direct_sound_samples/cries/cacturne.bin"

	.align 2
Cry_Baltoy::
	.incbin "sound/direct_sound_samples/cries/baltoy.bin"

	.align 2
Cry_Claydol::
	.incbin "sound/direct_sound_samples/cries/claydol.bin"

	.align 2
Cry_Lunatone::
	.incbin "sound/direct_sound_samples/cries/lunatone.bin"

	.align 2
Cry_Solrock::
	.incbin "sound/direct_sound_samples/cries/solrock.bin"

	.align 2
Cry_Feebas::
	.incbin "sound/direct_sound_samples/cries/feebas.bin"

	.align 2
Cry_Milotic::
	.incbin "sound/direct_sound_samples/cries/milotic.bin"

	.align 2
Cry_Absol::
	.incbin "sound/direct_sound_samples/cries/absol.bin"

	.align 2
Cry_Meditite::
	.incbin "sound/direct_sound_samples/cries/meditite.bin"

	.align 2
Cry_Medicham::
	.incbin "sound/direct_sound_samples/cries/medicham.bin"

	.align 2
Cry_Spheal::
	.incbin "sound/direct_sound_samples/cries/spheal.bin"

	.align 2
Cry_Sealeo::
	.incbin "sound/direct_sound_samples/cries/sealeo.bin"

	.align 2
Cry_Walrein::
	.incbin "sound/direct_sound_samples/cries/walrein.bin"

	.align 2
Cry_Clamperl::
	.incbin "sound/direct_sound_samples/cries/clamperl.bin"

	.align 2
Cry_Huntail::
	.incbin "sound/direct_sound_samples/cries/huntail.bin"

	.align 2
Cry_Gorebyss::
	.incbin "sound/direct_sound_samples/cries/gorebyss.bin"

	.align 2
Cry_Lileep::
	.incbin "sound/direct_sound_samples/cries/lileep.bin"

	.align 2
Cry_Cradily::
	.incbin "sound/direct_sound_samples/cries/cradily.bin"

	.align 2
Cry_Anorith::
	.incbin "sound/direct_sound_samples/cries/anorith.bin"

	.align 2
Cry_Armaldo::
	.incbin "sound/direct_sound_samples/cries/armaldo.bin"

	.align 2
Cry_Beldum::
	.incbin "sound/direct_sound_samples/cries/beldum.bin"

	.align 2
Cry_Metang::
	.incbin "sound/direct_sound_samples/cries/metang.bin"

	.align 2
Cry_Metagross::
	.incbin "sound/direct_sound_samples/cries/metagross.bin"

	.align 2
Cry_Bagon::
	.incbin "sound/direct_sound_samples/cries/bagon.bin"

	.align 2
Cry_Shelgon::
	.incbin "sound/direct_sound_samples/cries/shelgon.bin"

	.align 2
Cry_Regirock::
	.incbin "sound/direct_sound_samples/cries/regirock.bin"

	.align 2
Cry_Regice::
	.incbin "sound/direct_sound_samples/cries/regice.bin"

	.align 2
Cry_Registeel::
	.incbin "sound/direct_sound_samples/cries/registeel.bin"

	.align 2
Cry_Castform::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Volbeat::
	.incbin "sound/direct_sound_samples/cries/volbeat.bin"

	.align 2
Cry_Illumise::
	.incbin "sound/direct_sound_samples/cries/illumise.bin"

	.align 2
Cry_Poochyena::
	.incbin "sound/direct_sound_samples/cries/poochyena.bin"

	.align 2
Cry_Mightyena::
	.incbin "sound/direct_sound_samples/cries/mightyena.bin"

	.align 2
Cry_Dusclops::
	.incbin "sound/direct_sound_samples/cries/dusclops.bin"

	.align 2
Cry_Sableye::
	.incbin "sound/direct_sound_samples/cries/sableye.bin"

	.align 2
Cry_Mawile::
	.incbin "sound/direct_sound_samples/cries/mawile.bin"

	.align 2
Cry_Aron::
	.incbin "sound/direct_sound_samples/cries/aron.bin"

	.align 2
Cry_Lairon::
	.incbin "sound/direct_sound_samples/cries/lairon.bin"

	.align 2
Cry_Aggron::
	.incbin "sound/direct_sound_samples/cries/aggron.bin"

	.align 2
Cry_Relicanth::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Luvdisc::
	.incbin "sound/direct_sound_samples/cries/luvdisc.bin"

	.align 2
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cries/groudon.bin"

	.align 2
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cries/kyogre.bin"

	.align 2
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/rayquaza.bin"

	.align 2
Cry_Salamence::
	.incbin "sound/direct_sound_samples/cries/salamence.bin"

	.align 2
Cry_Breloom::
	.incbin "sound/direct_sound_samples/cries/breloom.bin"

	.align 2
Cry_Shroomish::
	.incbin "sound/direct_sound_samples/cries/shroomish.bin"

	.align 2
Cry_Linoone::
	.incbin "sound/direct_sound_samples/cries/linoone.bin"

	.align 2
Cry_Tropius::
	.incbin "sound/direct_sound_samples/cries/tropius.bin"

	.align 2
Cry_Wailmer::
	.incbin "sound/direct_sound_samples/cries/wailmer.bin"

	.align 2
Cry_Zigzagoon::
	.incbin "sound/direct_sound_samples/cries/zigzagoon.bin"

	.align 2
Cry_Exploud::
	.incbin "sound/direct_sound_samples/cries/exploud.bin"

	.align 2
Cry_Loudred::
	.incbin "sound/direct_sound_samples/cries/loudred.bin"

	.align 2
Cry_Wailord::
	.incbin "sound/direct_sound_samples/cries/wailord.bin"

	.align 2
Cry_Whismur::
	.incbin "sound/direct_sound_samples/cries/whismur.bin"

	.align 2
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cries/snorunt.bin"

	.align 2
Cry_Latios::
	.incbin "sound/direct_sound_samples/cries/latios.bin"

	.align 2
Cry_Jirachi::
	.incbin "sound/direct_sound_samples/cries/jirachi.bin"

	.align 2
Cry_Deoxys::
	.incbin "sound/direct_sound_samples/cries/deoxys.bin"

	.align 2
Cry_Chimecho::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Guthling::
	.incbin "sound/direct_sound_samples/cries/GodChicks.bin"

	.align 2
Cry_Guthbird::
	.incbin "sound/direct_sound_samples/cries/GodChicks.bin"

	.align 2
Cry_Guthraptor::
	.incbin "sound/direct_sound_samples/cries/GodChicks.bin"

	.align 2
Cry_Zamling::
	.incbin "sound/direct_sound_samples/cries/GodChicks.bin"

	.align 2
Cry_Zambird::
	.incbin "sound/direct_sound_samples/cries/GodChicks.bin"

	.align 2
Cry_Zamohawk::
	.incbin "sound/direct_sound_samples/cries/GodChicks.bin"

	.align 2
Cry_Saraling::
	.incbin "sound/direct_sound_samples/cries/GodChicks.bin"

	.align 2
Cry_Sarabird::
	.incbin "sound/direct_sound_samples/cries/GodChicks.bin"

	.align 2
Cry_Saraowl::
	.incbin "sound/direct_sound_samples/cries/GodChicks.bin"

	.align 2
Cry_Chick::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Chicken_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Dreadfowl::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Chicken_Varrock_Form::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Chicken_Diving_Form::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Chicken_Karamja_Form::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Chicken_Death_Form::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Chicken_Bandosian_Form::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Chicken_War_Form::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Rooster_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Ernest::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Rooster_Karamja_Form::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Oomlie::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Rooster_Bandosian_Form::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Chicken_Famine_Form::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Rooster_Varrock_Form::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Chicken_Pestilence_Form::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Chicken_Lizard_Form::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Chicken_Undead_Form::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Chicken_Mystery_Form::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_EvilChicken::
	.incbin "sound/direct_sound_samples/cries/blaziken.bin"

	.align 2
Cry_Swordchick::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Newtroost::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Calf::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Cow::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Super_Cow::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Cow_Dairy_Form::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Cow_Undead_Form::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Cow_Chocolate_Form::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Cow_Strawberry_Form::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Cow_Vanilla_Form::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Cow_Harlequin_Form::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_SkeletalOx_Female_Form::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Bull::
	.incbin "sound/direct_sound_samples/cries/tauros.bin"

	.align 2
Cry_Bull_Elder_Form::
	.incbin "sound/direct_sound_samples/cries/tauros.bin"

	.align 2
Cry_SkeletalOx_Male_Form::
	.incbin "sound/direct_sound_samples/cries/tauros.bin"

	.align 2
Cry_Trojan_Cow::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Cow_Plague_Form::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Minotaur_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/tauros.bin"

	.align 2
Cry_Minotaur_Rune_Form::
	.incbin "sound/direct_sound_samples/cries/tauros.bin"

	.align 2
Cry_Unicow::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Rat_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Rat_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Brine_Rat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Rat_Blessed_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rat_Hell_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Rat_Hell_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shell_Rat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rat_Crypt_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Rat_Crypt_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Warped_Rat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zombie_Rat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Rat_Dungeon_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rat_King_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Rat_King_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Albino_Rat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Angry_Rat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Experiment_2_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lamb::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Sheep_White_Form::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Sheep_Plague_Form::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Sheep_Black_Form::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Ram_Fluffy_Form::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Ram_Shaggy_Form::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Ram_Golden_Form::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Sheep_Pirate_Form::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Goat_Billy_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Goat_Desert_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Goat_Mountain_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Gorak::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sardine::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Herring::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Trout_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Swordfish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Trout_Leaping_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sturgeon::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Trout_Tropical_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sailfish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Thallasus::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bass::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Salmon_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shark_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Fury_Shark::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Salmon_Leaping_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shark_GreatWhite_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shark_Tiger_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Mackerel::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Catfish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shark_Baron_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tarpon::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Seerfish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_DesertSole::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sillago::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wobbegong::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Karambwanj::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Karambwan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Whitefish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Beltfish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Manta_Ray::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cod::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rainbow::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shark_Golden_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pike::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkfish_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_AnglerFish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Carp::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkfish_Fresh_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkfish_Golden_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_GoblinFish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pet_Fish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Gilbert::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cavefish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rocktail::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Eel_Slimy_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Eel_Cave_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Eel_Sacred_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Eel_Lava_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Eel_Infernal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Eel_Mottled_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Eel_Short_Finned_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Eel_Salve_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Eel_Dusk_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cave_Moray::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Vile_Fish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Piglet::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_Pig::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_Pigzilla::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_Puppy_Pup_Form::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Puppy_Mutt_Form::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Terrier::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Sheepdog::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Dalmatian::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Greyhound::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Bulldog::
	.incbin "sound/direct_sound_samples/cries/snubbull.bin"

	.align 2
Cry_Labrador::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Corgi::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Terror_Dog::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Stray_Dog::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Muncher::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Hellpuppy::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Hellhound::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Cerberus::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Kitten::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Cat_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Cat_Overgrown_Form::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Cat_Lazy_Form::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Cat_Wily_Form::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Cat_Purple_Form::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Cat_Hell_Form::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Cat_Post_Form::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Cat_Sunken_Form::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Bob::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Evil_Bob::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Pet_Rock::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Rock_Polished_Form::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Pillar::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Rock_Soup::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Slagilith::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Rock_Strange_Form::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Rock_Golden_Form::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Party_Rock::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Strykewyrm_Freezy_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Strykewyrm_Leafy_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Strykewyrm_Sandy_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Strykewyrm_Wildy_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_Pit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_Poison_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_King_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_Grave_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_Corrupted_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_Reanimated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_Gauntlet_Crystalline_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_Gauntlet_Corrupted_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_Khazard_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpion_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scorpia::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dreadnip::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Peepling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sneakrpeep::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Runtstable::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Basilisk::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Baby_Mole::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Mole::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Squirrel::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ravenling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Raven_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Raven_Nevermore_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Raven_Spooky_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Raven_Crystal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crow::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Magpie::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Grey_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Red_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Gold_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Vultling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Vulture::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pengling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penguin::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penguin_Clockwork_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_The_Thing::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ping::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pong::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penguin_McGraw_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penguin_Spy_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penguin_Agent_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penguin_Disguise_Cactus_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penguin_Disguise_Rock_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penguin_Disguise_Bush_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penguin_Disguise_Box_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_ExExParrot::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Broav::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tooths::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rune_Guardian::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Gnomey::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sparkles::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Bat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Warped_Bat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Albino_Bat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bat_Box_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Fruit_Bat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_VampyreBat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Deathwing::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shaikah::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Growler::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Phoenling_Rebirth_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Phoenling_Reborn_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Phoenix_Rebirth_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Phoenix_Reborn_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Plant_Strange_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Plant_Stranger_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_EvilTurnip::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Creature_Cute_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Creature_Evil_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Baby_Yak::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yak_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yak_Pack_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yak_Sacred_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yak_ClueScroll_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yak_Undead_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yak_Snack_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Minitrice::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cockatrice::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Guthatrice::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zamatrice::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Saratrice::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Corxatrice::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Vulatrice::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pengatrice::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chocatrice::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sproutling_Summer_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sproutling_Spring_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sproutling_Winter_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sproutling_Autumn_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rue::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monty::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zygomite::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssaling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_Minion_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_Demon_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_Sire_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_Leech_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_Parasite_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_Lurker_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_Walker_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_Titan_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tz_Kih::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tz_Kek::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tok_Xil::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tz_Kih_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ket_Dill::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ket_Zek::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yt_HurKot::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yt_MejKot::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_TzRek_Jad::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_TzTok_Jad::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_JalTok_Jad::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jal_MejRah::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jal_Ak::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jal_Xil::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jal_Nib::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jal_ImKot::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jal_Zek::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_TzKal_Zuk::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Duckling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Swan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Duck_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Mega_Duck::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Duck_Cart_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Platypode::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Platypus::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Fledgling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_Guardian_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_King_Range_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_King_Magic_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_King_Melee_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_King_Range_Mega_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_King_Magic_Mega_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_King_Melee_Mega_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chaos_Ele::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chaos_Ele_Mega_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bandling::
	.incbin "sound/direct_sound_samples/cries/GodChicks.bin"

	.align 2
Cry_Bandbird::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bandeagle::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zaroling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zarobird::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zaraven::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sereling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Serebird::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Serepea::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Frogspawn::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Frog_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Frog_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Frog_Royal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Frog_Bloated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Frog_Balloon_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Toad_Barker_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Frogeel::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spiderling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Giant_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_DeadlyRed_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Jungle_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Blessed_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Huge_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Night_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Ice_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Eek::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_MinstrlWeb::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sarachnis::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Venenatis::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spidine::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crayfish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shrimp::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lobster_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lobster_Golden_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lobster_Giant_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lobster_Heim_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lobster_Obsidian_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crab_Red_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Crab_Red_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crab_Moss_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Crab_Moss_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crab_RumPumped_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Crab_RumPumped_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crab_Dark_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Crab_Dark_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crab_Grey_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Crab_Grey_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Knife_Crab::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Heim_Crab::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_WebSnipper::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Blue_Crab::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crablet_First_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crablet_Second_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crablet_Third_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crablet_Forth_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crablet_Fifth_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crawler_Cave_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crawler_Chasm_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crawler_Monstrous_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Winston::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tortoise_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tortoise_Warped_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tortoise_War_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Valluta::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sea_Turtle::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sea_Turtle_Treasure_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Herbert::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Xinachto::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cave_Slime::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jelly_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jelly_Warped_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jelly_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_AbbySpectr::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Salamander_Green_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Salamander_Orange_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Salamander_Red_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Salamander_Black_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Salamander_Augmented_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Gecko::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chameleon::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodveld::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodveld_Insatiable_Physical_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodveld_Insatiable_Special_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodveld_Mutated_Physical_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodveld_Mutated_Special_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Reaver::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Armaling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Armabird::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Armafalcon::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ungodling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ungodbird::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ungodgeon::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tumekling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tumekbird::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tumekibis::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kerrit::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Snuffle::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Popoca::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Choloa::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Durzag::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yakamaru::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chompy::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jubbly::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jubster::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Terrorbird_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Terrorbird_Warped_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Terrorbird_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Juvenile_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Fenris_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_White_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rover::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Dire_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Jungle_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Skoll_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Desert_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Hati_Hati::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Fox::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Inari::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Helwyr::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bird_Nest::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Birds_Nest_God_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pigeon::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pheasant::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rocling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Roc::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Foal::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Unicorn_White_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Unicorn_Stallion_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Unicorn_Black_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Unicorn_Angry_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Unicorn_Reanimated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Starlight::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pawya::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Grenwall::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bear_Cub::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bear_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bear_Reanimated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bear_Gauntlet_Crystalline_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Callisto::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Polar_Bear_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Polar_Bear_PBJ_Agent_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Polar_Bear_Arctic_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Polar_Bear_Nanuq_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bear_Grizzly_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kendall::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bear_Gauntlet_Corrupted_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bear_Angry_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Graahk_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Graahk_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dust_Devil::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_SmokeDevil::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_SmokeDevil_Nuclear_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_ChokeDevil::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_SmokeDevil_Thermonuclear_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hatchling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragonling_Green_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_Green_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_Brutal_Green_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragonling_Blue_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_Blue_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_Brutal_Blue_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragonling_Red_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_Red_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_Brutal_Red_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragonling_Black_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_Black_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_Brutal_Black_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_ThreeHeaded_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Elvarg::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_King_Black_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dragon_Queen_Black_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hand_Creeping_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hand_Crawling_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hand_Skeletal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hand_Crushing_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hand_Zombie_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Turoth::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Turoth_Mightiest_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Big_Turoth::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sockroth::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lilrask::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kurask::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kurask_King_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kurask_Overlord_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Polar_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Sabre_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Spotted_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Dark_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Dashing_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Wild_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Prickly_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Razor_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Big_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_DesertDevil_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Feldip_Weasel_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Barbed_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Diseased_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kebbit_Chocolate_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkey_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkey_Ninja_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Gorilla_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkey_Zombie_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Gorilla_Ancient_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkey_Harmless_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkey_Ghost_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Gorilla_Ayuni_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Gorilla_Leeuni_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Gorilla_Eruni_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkey_Karamja_Baby_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkey_Karamja_Adult_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Larupia_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Larupia_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kyatt_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kyatt_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crabling::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rock_Crab_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rock_Crab_Giant_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rock_Crab_Ammonite_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rock_Crab_Giant_Ammonite_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rock_Crab_Sand_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rock_Crab_Giant_Sand_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rock_Crab_Swamp_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rock_Crab_Giant_Swamp_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crab_Granite_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lobster_Granite_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lobster_Rock_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rabbit::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolperting::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bunyip::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_TalonBeast_Talon_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_TalonBeast_Nail_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ferret::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Toy_Mouse::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Toy_Doll::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Toy_Soldier::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cat_Clockwork_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Magicarpet::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Anichair::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Exoraxe::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spookaxe::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dobbin::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Marionette::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_DragonKite::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Animour::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dead_Tree::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jadinko::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Killerwatt::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Mackers::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Turkey_Female_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Turkey_Male_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Turkey_Protestor_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Toucan_Tenacious_Male_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Toucan_Tenacious_Female_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Toucan_Tuai_Leit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jellyfish_Blubber_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jellyfish::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pure::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rune::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Essence::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Seagull_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pelican::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Albatross::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Seagull_Hattenkrapper_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Seagull_Koppenploppen_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Seagull_Steven_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ibis::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_DesertWyrm::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wyrm::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Snake_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cobra_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cobra_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Juna::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Snake_Sea_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Big_Snake_Sea_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Thingumwut::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Experiment_3_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cabbage::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ughtanki::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Camel::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Camel_Warrior_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_BalanceEle::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Larva_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Worker_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Soldier_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Guardian_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Queen_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Queen_Mega_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Paragon_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Corrupted_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Marauder_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_King_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Dung_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kalphite_Reanimated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_Demon_Reanimated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bat_Gauntlet_Corrupted_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bat_Gauntlet_Crystalline_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodveld_Reanimated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dark_Beast_Gauntlet_Corrupted_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dark_Beast_Gauntlet_Crystalline_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dark_Beast_Pup_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dark_Beast_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dark_Beast_Sotetseg_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Experiment_4_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Experiment_5_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ganodermic_Beast::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Grifolapine::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Grifolaroo::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sporaxe::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Headless_Beast::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Behemoth_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Behemoth_Adolscent_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Siege_Beast::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bulwark_Beast::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Behemoth_Gluttonous_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Behemoth_Runebound_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Stomp::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hope_Devourer::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Karamthulu_Overlord::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Light_Creature::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Minotaur_Reanimated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Monkey_Reanimated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rat_Gauntlet_Corrupted_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rat_Gauntlet_Crystalline_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rat_Fungal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sparky::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Corpse_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Fever_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Lava_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Shadow_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Stalker::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Soulseeker::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Stalker_Sentinel_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Night_Gazer::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Plane_Freezer::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_World_Gorger::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Flesh_Monger::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shadow_Forger::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Veil_Ripper::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Unicorn_Gauntlet_Corrupted_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Unicorn_Gauntlet_Crystalline_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Cave_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wolf_Dragon_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shadow_Hound::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Border_Collie::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodhound::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Guard_Dog::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lycurgus::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yak_Moorrissey_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yak_Robin_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Yak_Yaktrick_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cabbage_Sister_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cabbage_Crispy_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Strykewyrm_Mini_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crocodile_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crocodile_Mutadile_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crocodile_Ankh_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crocodile_Ukunduka_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodveld_Insatiable_Mutated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodveld_Acidic_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodveld_Vampiric_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Bloodveld_RS3_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Beaver::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Giant_Beaver::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Racoon::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ralph::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rocky::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Honey_Badger::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Squirrel_Giant_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Squirrel_Australian_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jade_Vine::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Klik::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jackalope::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Imp::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Lesser_RS3_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Greater_RS3_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Kalgerion_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Thundereous_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Ripper_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Lesser_OSRS_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Greater_OSRS_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Tstanon_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Tormented_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Delrith::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Lesser_Tongue_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Greater_Tongue_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Zakln_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Pummeler_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Chocolate_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Lesser_Black_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Greater_Black_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Balfrug_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Jungle_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Riftsplitter_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Snow_Imp::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Ice_OSRS_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Ice_RS3_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Bloodchiller_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Demon_Reanimated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kril_Tsutsaroth::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pyrefiend::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pyrelord::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Waterfiend::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Waterlord::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Icefiend::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Icelord::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Impling_Baby_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Magpie_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Dragon_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Kingly_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Lucky_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Penance_Spawn::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penance_Healer::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penance_Ranger::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penance_Runner::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penance_Fighter::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penance_Queen::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Penance_King::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Void_Leech::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Void_Torcher::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Void_Shifter::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Void_Brawler::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Void_Defiler::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Void_Splatter::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Void_Ravager::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Void_Spinner::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Void_Drone::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Void_Queen::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Anchovy::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Anchovy_Pizza_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Red_Eye::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Flatfish::
	.incbin "sound/direct_sound_samples/cries/muk.bin"

	.align 2
Cry_Bouldabass::
	.incbin "sound/direct_sound_samples/cries/mew.bin"

	.align 2
Cry_Mudskipper::
	.incbin "sound/direct_sound_samples/cries/mewtwo.bin"

	.align 2
Cry_Basilisk_Baby_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Basilisk_RS3_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Basilisk_OSRS_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Basilisk_Knight_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Ungael_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Crypt_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_Temple_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Spider_ApeAtoll_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Catablepon::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Protomastyx::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Tyrannomastyx::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pig_War_Form::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_Pig_Prayer_Form::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_Pig_Pack_Form::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_Herbiboar::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Goat_Clay_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Goat_SacredClay_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Goat_PrimordialClay_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shadeel::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Golem_Titan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Moss_Titan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Iron_Titan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Steel_Titan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lava_Titan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Obsidian_Golem::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Swamp_Titan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ice_Titan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Fire_Titan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Geysir_Titan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dark_Core::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Corporeal_Beast::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Corporeal_Beast_Zanik_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Compost_Mound::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ent::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Derwen::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cockroach_Drone::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cockroach_Worker::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cockroach_Soldier::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cockroach_Warped_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Fiara::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Cave_Bug::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Malcolm::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Meerkats::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Origami_Balloon::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Krill_Balloon::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Balloon_Goat::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_Mother::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Gelatinnoth::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_Daughter::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_Reanimated_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dagannoth_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Flambeed::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_AgrithNaNa::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Karamel::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Dessourt::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sharkizard::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Basstoise::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Raventzhaar::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wall_Beast::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wall_Beast_Mega_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sourhog::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hand_Farmhand_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hand_Stuffed_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hand_BrokenFingers_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hand_DeadHand_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Hand_Dungeoneering_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Snake_Desert_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Snake_Poison_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Snake_Swamp_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Icxan::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Skeletal_Wyvern::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Wyvern::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Impling_Gourmet_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Earth_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Young_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Pirate_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Ninja_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Zombie_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Eclectic_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Crystal_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Nature_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Essence_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Divine_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Impling_Spirit_Form::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Araxyte_Baby::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Araxyte_Acidic::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Araxyte_Mirrorback::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Araxyte_Pulsing::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Araxxor::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Araxxi::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Glacor_Enduring_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Glacor_Sapping_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Glacor_Unstable_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Glacor::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Glacor_Arch_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jadinko_Common_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jadinko_Male_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Jadinko_Queen::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Ruby_Harvest::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Sapphire_Glacialis::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Snow_Knight::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Black_Warlock::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Forge_Regent::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Guthixian_Butterfly::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Charming_Moth::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Treborn::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Draugen::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Macaw::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_The_Illusive::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Doubt::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Everlasting::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Untouchable::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Inadequancy::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Baby::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Grey_Baby::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Red_Baby::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Cobalt::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Viridian::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Crystal::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Plutonial::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Mechanized::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Crimson::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Black::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Chinchompa_Giant::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Vulture_RSHD_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Vulture_Pink_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Vulture_OSRS_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Vulture_RS3_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Beagle::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pug::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Huskie::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Shiba::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Polar_Bear_Punished::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Lobstrocity::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Salamander_Yellow_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_DeepSea_Walker::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_DeepSea_Leech::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_DeepSea_Guardian::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Kipple_Nano::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Coral_Guardian::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Rewards_Guardian::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Baboon_Normal_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Baboon_Mage_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Baboon_Shaman_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Baboon_Thrower_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Baboon_Cursed_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Baboon_Thrall_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Baboon_Volatile_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Baboon_BaBa_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scarab_Spitting_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scarab_Soldier_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scarab_Arcane_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Scarab_Kephri_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Crocodile_Red_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zebak::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Camel_Bank_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Slime_LilGloop::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Slime_King::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Graahk_Forsaken_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zygomite_Magical_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zygomite_Zanarian_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zygomite_Arcspore_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zygomite_Daemoncap_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zygomite_Ancient_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zulrah_Serpentine_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zulrah_Magma_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Zulrah_Tanzanite_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Pig_Summoning_Form::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_TzTok_Jad_HD_Mega_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_TzTok_Jad_RS3_Mega_Form::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Abyssal_Guardian::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
Cry_Skotizo::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"


	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_Phoneme_1::
	.incbin "sound/direct_sound_samples/phonemes/01.bin"

	.align 2
DirectSoundWaveData_Phoneme_2::
	.incbin "sound/direct_sound_samples/phonemes/02.bin"

	.align 2
DirectSoundWaveData_Phoneme_3::
	.incbin "sound/direct_sound_samples/phonemes/03.bin"

	.align 2
DirectSoundWaveData_Phoneme_4::
	.incbin "sound/direct_sound_samples/phonemes/04.bin"

	.align 2
DirectSoundWaveData_Phoneme_5::
	.incbin "sound/direct_sound_samples/phonemes/05.bin"

	.align 2
DirectSoundWaveData_Phoneme_6::
	.incbin "sound/direct_sound_samples/phonemes/06.bin"

	.align 2
DirectSoundWaveData_Phoneme_7::
	.incbin "sound/direct_sound_samples/phonemes/07.bin"

	.align 2
DirectSoundWaveData_Phoneme_8::
	.incbin "sound/direct_sound_samples/phonemes/08.bin"

	.align 2
DirectSoundWaveData_Phoneme_9::
	.incbin "sound/direct_sound_samples/phonemes/09.bin"

	.align 2
DirectSoundWaveData_Phoneme_10::
	.incbin "sound/direct_sound_samples/phonemes/10.bin"

	.align 2
DirectSoundWaveData_Phoneme_11::
	.incbin "sound/direct_sound_samples/phonemes/11.bin"

	.align 2
DirectSoundWaveData_Phoneme_12::
	.incbin "sound/direct_sound_samples/phonemes/12.bin"

	.align 2
DirectSoundWaveData_Phoneme_13::
	.incbin "sound/direct_sound_samples/phonemes/13.bin"

	.align 2
DirectSoundWaveData_Phoneme_14::
	.incbin "sound/direct_sound_samples/phonemes/14.bin"

	.align 2
DirectSoundWaveData_Phoneme_15::
	.incbin "sound/direct_sound_samples/phonemes/15.bin"

	.align 2
DirectSoundWaveData_Phoneme_16::
	.incbin "sound/direct_sound_samples/phonemes/16.bin"

	.align 2
DirectSoundWaveData_Phoneme_17::
	.incbin "sound/direct_sound_samples/phonemes/17.bin"

	.align 2
DirectSoundWaveData_Phoneme_18::
	.incbin "sound/direct_sound_samples/phonemes/18.bin"

	.align 2
DirectSoundWaveData_Phoneme_19::
	.incbin "sound/direct_sound_samples/phonemes/19.bin"

	.align 2
DirectSoundWaveData_Phoneme_20::
	.incbin "sound/direct_sound_samples/phonemes/20.bin"

	.align 2
DirectSoundWaveData_Phoneme_21::
	.incbin "sound/direct_sound_samples/phonemes/21.bin"

	.align 2
DirectSoundWaveData_Phoneme_22::
	.incbin "sound/direct_sound_samples/phonemes/22.bin"

	.align 2
DirectSoundWaveData_Phoneme_23::
	.incbin "sound/direct_sound_samples/phonemes/23.bin"

	.align 2
DirectSoundWaveData_Phoneme_24::
	.incbin "sound/direct_sound_samples/phonemes/24.bin"

	.align 2
DirectSoundWaveData_Phoneme_25::
	.incbin "sound/direct_sound_samples/phonemes/25.bin"

	.align 2
DirectSoundWaveData_Phoneme_26::
	.incbin "sound/direct_sound_samples/phonemes/26.bin"

	.align 2
DirectSoundWaveData_Phoneme_27::
	.incbin "sound/direct_sound_samples/phonemes/27.bin"

	.align 2
DirectSoundWaveData_Phoneme_28::
	.incbin "sound/direct_sound_samples/phonemes/28.bin"

	.align 2
DirectSoundWaveData_Phoneme_29::
	.incbin "sound/direct_sound_samples/phonemes/29.bin"

	.align 2
DirectSoundWaveData_Phoneme_30::
	.incbin "sound/direct_sound_samples/phonemes/30.bin"

	.align 2
DirectSoundWaveData_Phoneme_31::
	.incbin "sound/direct_sound_samples/phonemes/31.bin"

	.align 2
DirectSoundWaveData_Phoneme_32::
	.incbin "sound/direct_sound_samples/phonemes/32.bin"

	.align 2
DirectSoundWaveData_Phoneme_33::
	.incbin "sound/direct_sound_samples/phonemes/33.bin"

	.align 2
DirectSoundWaveData_Phoneme_34::
	.incbin "sound/direct_sound_samples/phonemes/34.bin"

	.align 2
DirectSoundWaveData_Phoneme_35::
	.incbin "sound/direct_sound_samples/phonemes/35.bin"

	.align 2
DirectSoundWaveData_Phoneme_36::
	.incbin "sound/direct_sound_samples/phonemes/36.bin"

	.align 2
DirectSoundWaveData_Phoneme_37::
	.incbin "sound/direct_sound_samples/phonemes/37.bin"

	.align 2
DirectSoundWaveData_Phoneme_38::
	.incbin "sound/direct_sound_samples/phonemes/38.bin"

	.align 2
DirectSoundWaveData_Phoneme_39::
	.incbin "sound/direct_sound_samples/phonemes/39.bin"

	.align 2
DirectSoundWaveData_Phoneme_40::
	.incbin "sound/direct_sound_samples/phonemes/40.bin"

	.align 2
DirectSoundWaveData_Phoneme_41::
	.incbin "sound/direct_sound_samples/phonemes/41.bin"

	.align 2
DirectSoundWaveData_Phoneme_42::
	.incbin "sound/direct_sound_samples/phonemes/42.bin"

	.align 2
DirectSoundWaveData_Phoneme_43::
	.incbin "sound/direct_sound_samples/phonemes/43.bin"

	.align 2
DirectSoundWaveData_Phoneme_44::
	.incbin "sound/direct_sound_samples/phonemes/44.bin"

	.align 2
DirectSoundWaveData_Phoneme_45::
	.incbin "sound/direct_sound_samples/phonemes/45.bin"

	.align 2
DirectSoundWaveData_Phoneme_46::
	.incbin "sound/direct_sound_samples/phonemes/46.bin"

	.align 2
DirectSoundWaveData_Phoneme_47::
	.incbin "sound/direct_sound_samples/phonemes/47.bin"

	.align 2
DirectSoundWaveData_Phoneme_48::
	.incbin "sound/direct_sound_samples/phonemes/48.bin"

	.align 2
DirectSoundWaveData_Phoneme_49::
	.incbin "sound/direct_sound_samples/phonemes/49.bin"

	.align 2
DirectSoundWaveData_Phoneme_50::
	.incbin "sound/direct_sound_samples/phonemes/50.bin"

	.align 2
DirectSoundWaveData_Phoneme_51::
	.incbin "sound/direct_sound_samples/phonemes/51.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
