	.align 2
voicegroup192::
	voice_keysplit_all voicegroup001  				//DRUMS
	voice_keysplit voicegroup005, KeySplitTable1 	//PIANO  (BRIGHT ACOUSTIC)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127 //OVERDRIVEN GUITAR
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115   //Synth bass 38 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  
	voice_keysplit voicegroup006, KeySplitTable2 //STRINGS


