Draynor_Bank_MapScripts::
	.byte 0


NPC_DraynorBank_Qutiedoll::
	lock
	namebox NPC_DraynorBank_Qutiedoll_Text_0
	msgbox NPC_DraynorBank_Qutiedoll_Text_1
	hidenamebox
	release
	end


NPC_DraynorBank_Purepker895::
	lock
	faceplayer
	namebox NPC_DraynorBank_Purepker895_Text_0
	msgbox NPC_DraynorBank_Purepker895_Text_1
	hidenamebox
	release
	end


NPC_DraynorBank_1337sp34kr::
	lock
	faceplayer
	namebox NPC_DraynorBank_1337sp34kr_Text_0
	msgbox NPC_DraynorBank_1337sp34kr_Text_1
	hidenamebox
	release
	end


NPC_DraynorBank_Elfinlocks::
	lock
	faceplayer
	namebox NPC_DraynorBank_Elfinlocks_Text_0
	msgbox NPC_DraynorBank_Elfinlocks_Text_1
	hidenamebox
	release
	end


NPC_DraynorBank_PilloryGuard::
	lock
	faceplayer
	namebox NPC_DraynorBank_PilloryGuard_Text_0
	msgbox NPC_DraynorBank_PilloryGuard_Text_1
	hidenamebox
	release
	end


NPC_DraynorBank_Qutiedoll_Text_0:
	.string "Qutiedoll$"

NPC_DraynorBank_Qutiedoll_Text_1:
	.string "How do you get behind the bank booth?$"

NPC_DraynorBank_Purepker895_Text_0:
	.string "Purepker895$"

NPC_DraynorBank_Purepker895_Text_1:
	.string "…$"

NPC_DraynorBank_1337sp34kr_Text_0:
	.string "1337sp34kr$"

NPC_DraynorBank_1337sp34kr_Text_1:
	.string "S331ing N4ts!$"

NPC_DraynorBank_Elfinlocks_Text_0:
	.string "Elfinlocks$"

NPC_DraynorBank_Elfinlocks_Text_1:
	.string "Buying 2k nats, no noob offers!$"

NPC_DraynorBank_PilloryGuard_Text_0:
	.string "Pillory Guard$"

NPC_DraynorBank_PilloryGuard_Text_1:
	.string "You would be best to watch yourself.\p"
	.string "Otherwise you're in for da cage!$"
