#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                          0
#define TRAINER_MAGGIE            			  1
//route 1
#define TRAINER_GOBLIN_1_ROUTE1			      2
#define TRAINER_GOBLIN_2_ROUTE1				  3
#define TRAINER_GOBLIN_3_ROUTE1               4
#define TRAINER_FARMER_ROUTE1                 5
#define TRAINER_RSN_ROUTE1					  6
//mill lane mill
#define TRAINER_TRAINER2_MILLLANEMILL                   7
#define TRAINER_TRAINER3_MILLLANEMILL                   8
#define TRAINER_TRAINER4_MILLLANEMILL                   9
#define TRAINER_MILLIE_MILLER_MILLLANEMILL                   10
//route 12
#define TRAINER_GOBLIN_4_ROUTE12              11
#define TRAINER_GOBLIN_5_ROUTE12              12
#define TRAINER_GOBLIN_6_ROUTE12              13
#define TRAINER_GOBLIN_7_ROUTE12              14
#define TRAINER_RSN_ROUTE12                   15
//route 4
#define TRAINER_SCAMMER_ROUTE4                16
#define TRAINER_FARMER_ROUTE4                 17
#define TRAINER_MUGGER_ROUTE4                 18
//route 6
#define TRAINER_MUGGER_ROUTE6                 19

//lumbridge castle gym

#define TRAINER_LUMBRIDGE_GYM1                20
#define TRAINER_LUMBRIDGE_GYM2                21
#define TRAINER_LUMBRIDGE_GYM3                22
#define TRAINER_LUMBRIDGE_GYM4                23
#define TRAINER_DUKE                          24

//lumbridge swamp
#define TRAINER_MUGGER_LUM_SWAMP              25
#define TRAINER_SKELETON_LUM_SWAMP            26
#define TRAINER_RSN_LUM_SWAMP                 27

#define TRAINER_MITHRILMAN1                      28
#define TRAINER_MITHRILMAN2                      29
#define TRAINER_MITHRILMAN3                      30
#define TRAINER_MITHRILMAN4                      31
#define TRAINER_MITHRILMAN5                      32
#define TRAINER_MITHRILMAN6                      33
#define TRAINER_MITHRILMAN7                      34
#define TRAINER_MITHRILMAN8                      35
#define TRAINER_MITHRILMAN9                      36
#define TRAINER_MITHRILMAN10                     37

#define TRAINER_TRAINER1_MILLLANEMILL            38
#define TRAINER_KARAMJAVOLCANO_HAM_ADMIN_PATTY        39
#define TRAINER_KARAMJAVOLCANO_HAM_GRUNT_1        40
#define TRAINER_KARAMJAVOLCANO_HAM_GRUNT_2      41 
#define TRAINER_KARAMJAVOLCANO_HAM_GRUNT_3      42
#define TRAINER_KARAMJAVOLCANO_HAM_GRUNT_4      43
#define TRAINER_KARAMJAVOLCANO_HAM_GRUNT_5      44
#define TRAINER_KARAMJAVOLCANO_HAM_GRUNT_6      45
#define TRAINER_KARAMJAVOLCANO_SKELETON_1      46
#define TRAINER_DRAYNOR_MANOR_COUNT_DRAYNOR      47
#define TRAINER_GOBLIN_4_ROUTE1               48
#define TRAINER_ROUTE2_TRAINER_1               49
#define TRAINER_ROUTE2_TRAINER_2               51
#define TRAINER_ROUTE2_TRAINER_3               52
#define TRAINER_ROUTE2_TRAINER_4               53
#define TRAINER_ROUTE2_TRAINER_5               54
#define TRAINER_ROUTE2_TRAINER_6               55
#define TRAINER_ROUTE2_TRAINER_7               56
#define TRAINER_LUM_SWAMP_GRASSTEETH                 57
#define TRAINER_WIZARDSTOWER_TRAINER_1               58
#define TRAINER_WIZARDSTOWER_TRAINER_2               59
#define TRAINER_WIZARDSTOWER_TRAINER_3               60
#define TRAINER_WIZARDSTOWER_TRAINER_4               61
#define TRAINER_WIZARDSTOWER_TRAINER_MYRTLE          62
#define TRAINER_DRAYNOR_MANOR_SKELETON_1          63
#define TRAINER_DRAYNOR_MANOR_SKELETON_2          64
#define TRAINER_DRAYNOR_MANOR_TRAINER_3          65
#define TRAINER_DRAYNOR_MANOR_SKELETON_4          66
#define TRAINER_DRAYNOR_MANOR_SKELETON_5          67
#define TRAINER_DRAYNOR_MANOR_SKELETON_6          68
#define TRAINER_DRAYNOR_MANOR_SKELETON_7          69
#define TRAINER_DRAYNOR_MANOR_SKELETON_8          70
#define TRAINER_ROUTE3_TRAINER_1                  71
//ROUTE 5
#define TRAINER_ROUTE5_CAPTAINTOCK                72
#define TRAINER_ROUTE5_WOODCUTTER                 73
//ROUTE10
#define TRAINER_ROUTE10_MONK                    74
#define TRAINER_ROUTE10_GOBLIN_1                75
#define TRAINER_ROUTE10_GOBLIN_2                76
//ROUTE8
#define TRAINER_ROUTE8_THIEF                    77
#define TRAINER_ROUTE8_NOOB                    78
#define TRAINER_ROUTE8_DnD                    79
#define TRAINER_ROUTE8_MINER_1                    80
#define TRAINER_ROUTE8_WOODCUTTER                    81
#define TRAINER_ROUTE8_MINER_2                    82
#define TRAINER_ROUTE8_WIZARD_AIR                    83
#define TRAINER_ROUTE8_WIZARD_WATER                    84
#define TRAINER_ROUTE8_WIZARD_EARTH                    85
#define TRAINER_ROUTE8_WIZARD_FIRE                    86
#define TRAINER_ROUTE8_WIZARD_MALIGNIUS_MORTIFER                    87
//ROUTE 9
#define TRAINER_ROUTE9_GOBLIN_1                    88
#define TRAINER_ROUTE9_GOBLIN_2                    89
#define TRAINER_ROUTE9_GOBLIN_3                    90
#define TRAINER_ROUTE9_GOBLIN_4                    91
#define TRAINER_ROUTE9_CHEF                   92
#define TRAINER_ROUTE9_MUGGER                   93
#define TRAINER_ROUTE9_GUTHIX_WIZARD                   94
#define TRAINER_ROUTE9_MINER_1                   95
#define TRAINER_ROUTE9_MINER_2                   96
//route12
#define TRAINER_ROUTE11_QUESTER                   97
#define TRAINER_ROUTE11_PIRATE                   98
#define TRAINER_ROUTE11_SAILOR                   99
#define TRAINER_ROUTE11_PvMer                   100
#define TRAINER_ROUTE11_GRACEFUL                   101
//FALADOR
#define TRAINER_FALADOR_MODTIMBO                   102
//LUMBRIDGE SWAMP CAVES
#define TRAINER_LUMBRIDGESWAMPCAVE_FISHERMAN_1                  103
#define TRAINER_LUMBRIDGESWAMPCAVE_SKELETON_1                  104
#define TRAINER_LUMBRIDGESWAMPCAVE_PVMER_1                   105
//DRAYNOR SEWERS
#define TRAINER_DRAYNORSEWERS_SKELETON_1                   106
#define TRAINER_DRAYNORSEWERS_SKELETON_2                   107
#define TRAINER_ROUTE6_FIREMAKER                   108
//ASGANIA DUNGEON
#define TRAINER_AsgarnianDungeon_MUGGER_1                   109
#define TRAINER_AsgarnianDungeon_PIRATE_1                   110
#define TRAINER_AsgarnianDungeon_PIRATE_2                   111
#define TRAINER_AsgarnianDungeon_PIRATE_3                   112
#define TRAINER_AsgarnianDungeon_PIRATE_4                   113
#define TRAINER_AsgarnianDungeon_GOBLIN_1                   114
#define TRAINER_AsgarnianDungeon_GOBLIN_2                   115
#define TRAINER_AsgarnianDungeon_QUESTER                   116
#define TRAINER_AsgarnianDungeon_PVM_1                   117
#define TRAINER_AsgarnianDungeon_PVM_2                   118
#define TRAINER_ROUTE6_GUARD_1               119

#define TRAINER_DWARVENMINES_BLACKKNIGHT     120
//FALADOR GYM
#define TRAINER_FALADOR_GYM_1                121
#define TRAINER_FALADOR_GYM_2                122
#define TRAINER_FALADOR_GYM_3                123
#define TRAINER_FALADOR_GYM_4                124
#define TRAINER_FALADOR_GYM_AMIKVARZE        125
#define TRAINER_FALADOR_HAIRDRESSER        126
//DWARVEN MINES
#define TRAINER_DWARVENMINES_SKILLER     127
#define TRAINER_DWARVENMINES_MINER     128
#define TRAINER_DWARVENMINES_DWARF_1     129
#define TRAINER_DWARVENMINES_DWARF_2     130
#define TRAINER_DWARVENMINES_DWARF_3     131
#define TRAINER_DWARVENMINES_DWARF_4     132
//ROUTE 24
#define TRAINER_ROUTE24_MUGGER     133
#define TRAINER_ROUTE24_WOODCUTTER_1     134
#define TRAINER_ROUTE24_WOODCUTTER_2     135
#define TRAINER_ROUTE24_GOBLIN_1     136
#define TRAINER_ROUTE24_GOBLIN_2     137
#define TRAINER_ROUTE24_GOBLIN_3     138
#define TRAINER_ROUTE24_GOBLIN_4     139
#define TRAINER_MUDSKIPPERPOINT_SLAYER     140
#define TRAINER_MUDSKIPPERPOINT_FISHERMAN_1     141
#define TRAINER_MUDSKIPPERPOINT_FISHERMAN_2     142
#define TRAINER_DEMONHEADGE     143
#define TRAINER_ROUTE40_DIVINER     144
#define TRAINER_PUB_SARIM_1     145
#define TRAINER_PUB_SARIM_2     146
#define TRAINER_PUB_SARIM_3     147
#define TRAINER_RimmingtonMines_Miner     148
#define TRAINER_RimmingtonMines_Ironman     149
#define TRAINER_RimmingtonMines_Slayer     150
#define TRAINER_DWARVENMINES_HAM    151
//ROUTE23
#define TRAINER_ROUTE23_TRAINER_1    152
#define TRAINER_ROUTE23_TRAINER_2    153
#define TRAINER_ROUTE23_TRAINER_3    154
#define TRAINER_ROUTE23_TRAINER_4    155
#define TRAINER_ROUTE23_TRAINER_COUPLE    156

#define TRAINER_RimmingtonMines_Slayer_1    157
#define TRAINER_RimmingtonMines_DRAGONBOT_1    158
#define TRAINER_RimmingtonMines_DRAGONBOT_2    159
#define TRAINER_Varrock_Max    160
#define TRAINER_Soffan_and_Quo    161
//BARBARIAN GYM
#define TRAINER_BARBARIAN_GYM_TRAINER_1    162
#define TRAINER_BARBARIAN_GYM_TRAINER_2    163
#define TRAINER_BARBARIAN_GYM_TRAINER_3    164
#define TRAINER_BARBARIAN_GYM_GUNTHOR      165
//ROUTE20
#define TRAINER_ROUTE20_TRAINER_1       166
#define TRAINER_ROUTE20_TRAINER_2       167
#define TRAINER_ROUTE20_TRAINER_3       168
#define TRAINER_ROUTE20_TRAINER_4       169
#define TRAINER_ROUTE20_DUO             170
//ROUTE18
#define TRAINER_ROUTE18_TRAINER_1       171
#define TRAINER_ROUTE18_TRAINER_2       172
#define TRAINER_ROUTE18_TRAINER_3       173
#define TRAINER_ROUTE18_TRAINER_4       174
#define TRAINER_ROUTE18_TRAINER_5       175
#define TRAINER_ROUTE18_TRAINER_6       176
//ROUTE13
#define TRAINER_ROUTE13_TRAINER_1       177
#define TRAINER_ROUTE13_TRAINER_2       178
#define TRAINER_ROUTE13_TRAINER_3       179
#define TRAINER_ROUTE13_TRAINER_4       180
#define TRAINER_ROUTE13_TRAINER_5       181
#define TRAINER_ROUTE13_TRAINER_6       182
#define TRAINER_ROUTE13_TRAINER_7       183
#define TRAINER_ROUTE13_TRAINER_8       184
//ROUTE14
#define TRAINER_ROUTE14_TRAINER_1       185
#define TRAINER_ROUTE14_TRAINER_2       186
//ROUTE15
#define TRAINER_ROUTE15_TRAINER_1       187
#define TRAINER_ROUTE15_TRAINER_2       188
#define TRAINER_ROUTE15_TRAINER_3       189
#define TRAINER_ROUTE15_TRAINER_4       190
#define TRAINER_ROUTE15_TRAINER_5       191
#define TRAINER_ROUTE15_TRAINER_6       192
//ROUTE16
#define TRAINER_ROUTE16_TRAINER_1       193
#define TRAINER_ROUTE16_TRAINER_2       194
#define TRAINER_ROUTE16_TRAINER_3       195
#define TRAINER_ROUTE16_TRAINER_4       196
#define TRAINER_ROUTE16_TRAINER_5       197
#define TRAINER_ROUTE16_TRAINER_6       198
//ROUTE17
#define TRAINER_ROUTE17_TRAINER_1       199
#define TRAINER_ROUTE17_TRAINER_2       200
//ROUTE38
#define TRAINER_ROUTE38_TRAINER_1       201
#define TRAINER_ROUTE38_TRAINER_2       202
#define TRAINER_ROUTE38_TRAINER_3       203
#define TRAINER_ROUTE38_TRAINER_4       204
#define TRAINER_ROUTE38_TRAINER_5       205
//ROUTE30
#define TRAINER_ROUTE30_TRAINER_1       206
#define TRAINER_ROUTE30_TRAINER_2       207
#define TRAINER_ROUTE30_TRAINER_3       208
#define TRAINER_ROUTE30_TRAINER_4       209
//VARROCK GYM
#define TRAINER_VARROCK_GYM_TRAINER_1       210
#define TRAINER_VARROCK_GYM_TRAINER_2       211
#define TRAINER_VARROCK_GYM_TRAINER_3       212
#define TRAINER_VARROCK_GYM_TRAINER_4       213
#define TRAINER_VARROCK_GYM_TRAINER_5       214
#define TRAINER_VARROCK_GYM_KING_ROALD       215
//
#define TRAINER_ROUTE18_TRAINER_7         216
#define TRAINER_ROUTE19_TRAINER_1         217
#define TRAINER_ROUTE13_TRAINER_9         218
#define TRAINER_PREZLEEK                219
#define TRAINER_NYCHANNEL               220
#define TRAINER_GERTRUDE               221
//LUMBRIDGE FOREST
#define TRAINER_LUMBRIDGEFOREST_WOODCUTTER1 222
#define TRAINER_LUMBRIDGEFOREST_BOT1 223

#define TRAINER_SINKHOLE_NPC_FORGOTTENWARRIOR_1 225
//ROUTe28
#define TRAINER_ROUTE28_TRAINER_1 226
#define TRAINER_ROUTE28_TRAINER_2 227
#define TRAINER_ROUTE28_TRAINER_3 228
#define TRAINER_ROUTE28_TRAINER_4 229
#define TRAINER_ROUTE28_TRAINER_5 230
//route29
#define TRAINER_ROUTE29_TRAINER_1 231
#define TRAINER_ROUTE29_TRAINER_2 232
#define TRAINER_ROUTE29_TRAINER_3 233
#define TRAINER_ROUTE29_TRAINER_4 234
#define TRAINER_ROUTE29_TRAINER_5 235
//ROUTE33
#define TRAINER_ROUTE33_GOBLIN1 236
#define TRAINER_ROUTE33_GOBLIN2 237
#define TRAINER_ROUTE33_ZAMORAK1 238
//VARROCK GYM
#define TRAINER_VARROCK_GYM_KINGROALD 239
#define TRAINER_VARROCK_GYM_1 240
#define TRAINER_VARROCK_GYM_2 241
#define TRAINER_VARROCK_GYM_3 242
#define TRAINER_VARROCK_GYM_4 243
//Lummy Forest
#define TRAINER_LUMBRIDGEFOREST_TRAINER_1 244
#define TRAINER_LUMBRIDGEFOREST_TRAINER_2 245
#define TRAINER_LUMBRIDGEFOREST_TRAINER_3 246
//AlKharid Gym
#define TRAINER_ALKHARID_GYM_TRAINER_1 247
#define TRAINER_ALKHARID_GYM_TRAINER_2 248
#define TRAINER_ALKHARID_GYM_TRAINER_3 249
#define TRAINER_ALKHARID_GYM_TRAINER_4 250
#define TRAINER_ALKHARID_GYM_PRINCE_ALI 251
//BARROWS
#define TRAINER_BARROWS_GUTHAN 252
#define TRAINER_MOD_SARNIE 253

//Route27
#define TRAINER_ROUTE27_TRAINER_1 254
#define TRAINER_ROUTE27_TRAINER_2 255
#define TRAINER_ROUTE27_TRAINER_3 256
#define TRAINER_ROUTE27_TRAINER_4 257
//ROUTE30
#define TRAINER_ROUTE25_TRAINER_1 258
#define TRAINER_ROUTE25_TRAINER_2 259
#define TRAINER_ROUTE25_TRAINER_3 260
//route39
#define TRAINER_ROUTE39_TRAINER_1 261
#define TRAINER_ROUTE39_TRAINER_2 262
#define TRAINER_ROUTE39_TRAINER_3 263
#define TRAINER_ROUTE39_TRAINER_4 264
#define TRAINER_ROUTE39_TRAINER_5 265
#define TRAINER_ROUTE39_TRAINER_6 266
#define TRAINER_ROUTE39_TRAINER_7 267
#define TRAINER_ROUTE39_TRAINER_8 268
//swamp cave
#define TRAINER_LUMBRIDGESWAMPCAVE_4 269
#define TRAINER_LUMBRIDGESWAMPCAVE_5 270
#define TRAINER_LUMBRIDGESWAMPCAVE_6 271
//musa point
#define TRAINER_MUSA_POINT_TRAINER_1 272
#define TRAINER_MUSA_POINT_TRAINER_2 273
#define TRAINER_MUSA_POINT_TRAINER_3 274
#define TRAINER_MUSA_POINT_TRAINER_4 275

#define TRAINER_SCAPEINK 276











// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      806
#define MAX_TRAINERS_COUNT                  864

#endif  // GUARD_CONSTANTS_OPPONENTS_H
