gText_Birch_Welcome::
	.string "Hello, there!\n"
	.string "Glad to see you again!\p"
	.string "Welcome back to PALLET TOWN.\p"
	.string "You and your rival really tried your\n"
	.string "best at the INDIGO LEAGUE, but it\l"
	.string "was just not enough.\p"
	.string "Despite that, I'm still proud that\n"
	.string "two trainers from my hometown came\l"
	.string "far in such a prestigious tournament!\p"
	.string "Now you're back in PALLET TOWN,\n"
	.string "and your POKéMON are at my lab.\p"
	.string "They really enjoy it here.\p"
	.string "Look…\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Oh, I remember the day you left\n"
	.string "PALLET TOWN for the first time\l"
	.string "together.\p"
	.string "Who would've known that the two of\n"
	.string "you would be best friends, now.\p"
	.string "I'm glad to witness that.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "…$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Why don't you come to my lab to\n"
	.string "pick up PIKACHU?\p"
	.string "I might even have a new objective\n"
	.string "for you.\p"
	.string "Let's do some paperwork.\n"
	.string "What was your name, again?"
	.string "$"

gText_Birch_SoItsPlayer::
	.string "Right…\n"
	.string "I see you filled in {PLAYER}{KUN}.$"

gText_Birch_YourePlayer::
	.string "Great!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}{KUN}!\p"
	.string "When you're ready, I'll see you\n"
	.string "at my lab!\p"
	.string "$"
