gText_Birch_Welcome::
	.string "Hello, there!\n"
	.string "Glad to see you again!\p"
	.string "Welcome back to PALLET TOWN.\p"
	.string "You and your rival really tried your\n"
	.string "best at the INDIGO LEAGUE, but it\l"
	.string "was just not enough.\p"
	.string "Despite that, I'm still proud that\n"
	.string "two trainers from my hometown came\l"
	.string "far in such a prestigious tournament!\p"
	.string "Now you're back in PALLET TOWN,\n"
	.string "and your POKéMON are at my lab.\p"
	.string "They really enjoy it here.\p"
	.string "Look…\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Oh, I remember the day you left\n"
	.string "PALLET TOWN for the first time\l"
	.string "together.\p"
	.string "Who would've known that the two of\n"
	.string "you would be best friends, now.\p"
	.string "I'm glad to witness that.\p"
	.string "\n"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
