Lumbridge_Church_MapScripts::
	.byte 0


Lumbridge_Church_Father_Aereck::
	lock
	faceplayer
	msgbox Lumbridge_Church_Father_Aereck_Text_0
	release
	end


Lumbridge_Church_NPC1::
	lock
	faceplayer
	msgbox Lumbridge_Church_NPC1_Text_0
	release
	end


Lumbridge_Church_NPC2::
	lock
	faceplayer
	msgbox Lumbridge_Church_NPC2_Text_0
	release
	end


Lumbridge_Church_NPC3::
	lock
	faceplayer
	msgbox Lumbridge_Church_NPC3_Text_0
	release
	end


Lumbridge_Church_Father_Aereck_Text_0:
	.string "Monsters dont really die.\p"
	.string "They will not be needing graves.\p"
	.string "Just take them to the bank.$"

Lumbridge_Church_NPC1_Text_0:
	.string "Praise be Saradomin!$"

Lumbridge_Church_NPC2_Text_0:
	.string "Bow to the great one!$"

Lumbridge_Church_NPC3_Text_0:
	.string "I love Lumbridge.\p"
	.string "Nothing happens.\p"
	.string "Town is safe and Zamorak and Saradomin\n"
	.string "won't wreck it over some light balls.$"
