	.align 1
gMetatiles_General::
	.incbin "data/tilesets/primary/general/metatiles.bin"

	.align 1
gMetatileAttributes_General::
	.incbin "data/tilesets/primary/general/metatile_attributes.bin"

	.align 1
gMetatiles_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatiles.bin"

	.align 1
gMetatileAttributes_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatile_attributes.bin"

	.align 1
gMetatiles_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatiles.bin"

	.align 1
gMetatileAttributes_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatile_attributes.bin"

	.align 1
gMetatiles_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatiles.bin"

	.align 1
gMetatileAttributes_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatile_attributes.bin"

	.align 1
gMetatiles_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatiles.bin"

	.align 1
gMetatileAttributes_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatile_attributes.bin"

	.align 1
gMetatiles_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatiles.bin"

	.align 1
gMetatileAttributes_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatile_attributes.bin"

	.align 1
gMetatiles_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatiles.bin"

	.align 1
gMetatileAttributes_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatile_attributes.bin"

	.align 1
gMetatiles_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatiles.bin"

	.align 1
gMetatileAttributes_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatile_attributes.bin"

	.align 1
gMetatiles_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatiles.bin"

	.align 1
gMetatileAttributes_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatile_attributes.bin"

	.align 1
gMetatiles_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatiles.bin"

	.align 1
gMetatileAttributes_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatile_attributes.bin"

	.align 1
gMetatiles_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatiles.bin"

	.align 1
gMetatileAttributes_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatile_attributes.bin"

	.align 1
gMetatiles_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatiles.bin"

	.align 1
gMetatileAttributes_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatile_attributes.bin"

	.align 1
gMetatiles_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatiles.bin"

	.align 1
gMetatileAttributes_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatile_attributes.bin"

	.align 1
gMetatiles_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatiles.bin"

	.align 1
gMetatileAttributes_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_attributes.bin"

	.align 1
gMetatiles_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatiles.bin"

	.align 1
gMetatileAttributes_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatile_attributes.bin"

	.align 1
gMetatiles_Shop::
	.incbin "data/tilesets/secondary/shop/metatiles.bin"

	.align 1
gMetatileAttributes_Shop::
	.incbin "data/tilesets/secondary/shop/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatile_attributes.bin"

	.align 1
gMetatiles_Cave::
	.incbin "data/tilesets/secondary/cave/metatiles.bin"

	.align 1
gMetatileAttributes_Cave::
	.incbin "data/tilesets/secondary/cave/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatile_attributes.bin"

	.align 1
gMetatiles_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatiles.bin"

	.align 1
gMetatileAttributes_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatile_attributes.bin"

	.align 1
gMetatiles_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatiles.bin"

	.align 1
gMetatileAttributes_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatile_attributes.bin"

	.align 1
gMetatiles_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatiles.bin"

	.align 1
gMetatileAttributes_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatile_attributes.bin"

	.align 1
gMetatiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatiles.bin"

	.align 1
gMetatileAttributes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatile_attributes.bin"

	.align 1
gMetatiles_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatiles.bin"

	.align 1
gMetatileAttributes_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatile_attributes.bin"

	.align 1
gMetatiles_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatiles.bin"

	.align 1
gMetatileAttributes_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatile_attributes.bin"

	.align 1
gMetatiles_Facility::
	.incbin "data/tilesets/secondary/facility/metatiles.bin"

	.align 1
gMetatileAttributes_Facility::
	.incbin "data/tilesets/secondary/facility/metatile_attributes.bin"

	.align 1
gMetatiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatiles.bin"

	.align 1
gMetatileAttributes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatile_attributes.bin"

	.align 1
gMetatiles_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatiles.bin"

	.align 1
gMetatileAttributes_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatiles.bin"

	.align 1
gMetatileAttributes_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatile_attributes.bin"

	.align 1
gMetatiles_Contest::
	.incbin "data/tilesets/secondary/contest/metatiles.bin"

	.align 1
gMetatileAttributes_Contest::
	.incbin "data/tilesets/secondary/contest/metatile_attributes.bin"

	.align 1
gMetatiles_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatiles.bin"

	.align 1
gMetatileAttributes_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatile_attributes.bin"

	.align 1
gMetatiles_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatiles.bin"

	.align 1
gMetatileAttributes_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatile_attributes.bin"

	.align 1
gMetatiles_Lab::
	.incbin "data/tilesets/secondary/lab/metatiles.bin"

	.align 1
gMetatileAttributes_Lab::
	.incbin "data/tilesets/secondary/lab/metatile_attributes.bin"

	.align 1
gMetatiles_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatiles.bin"

	.align 1
gMetatileAttributes_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatile_attributes.bin"

	.align 1
gMetatiles_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatiles.bin"

	.align 1
gMetatileAttributes_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatile_attributes.bin"

	.align 1
gMetatiles_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatiles.bin"

	.align 1
gMetatileAttributes_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatile_attributes.bin"

	.align 1
gMetatiles_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatiles.bin"

	.align 1
gMetatileAttributes_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatile_attributes.bin"

	.align 1
gMetatiles_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatiles.bin"

	.align 1
gMetatileAttributes_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatile_attributes.bin"

	.align 1
gMetatiles_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatiles.bin"

	.align 1
gMetatileAttributes_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatile_attributes.bin"

	.align 1
gMetatiles_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatiles.bin"

	.align 1
gMetatileAttributes_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatile_attributes.bin"

	.align 1
gMetatiles_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatiles.bin"

	.align 1
gMetatileAttributes_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatile_attributes.bin"

	.align 1
gMetatiles_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatiles.bin"

	.align 1
gMetatileAttributes_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatiles.bin"

	.align 1
gMetatileAttributes_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatile_attributes.bin"

	.align 1
gMetatiles_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatiles.bin"

	.align 1
gMetatileAttributes_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatile_attributes.bin"

	.align 1
gMetatiles_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatiles.bin"

	.align 1
gMetatileAttributes_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_attributes.bin"

	.align 1
gMetatiles_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatiles.bin"

	.align 1
gMetatileAttributes_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatiles.bin"

	.align 1
gMetatileAttributes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatile_attributes.bin"

	.align 1
gMetatiles_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatiles.bin"

	.align 1
gMetatileAttributes_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatile_attributes.bin"

	.align 1
gMetatiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatiles.bin"

	.align 1
gMetatileAttributes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_attributes.bin"

	.align 1
gMetatiles_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatiles.bin"

	.align 1
gMetatileAttributes_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatile_attributes.bin"

	.align 1
gMetatiles_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatiles.bin"

	.align 1
gMetatileAttributes_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatile_attributes.bin"

	.align 1
gMetatiles_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatiles.bin"

	.align 1
gMetatileAttributes_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatile_attributes.bin"

	.align 1
gMetatiles_PokeScapeOutdoors::
	.incbin "data/tilesets/primary/PokeScapeOutdoors/metatiles.bin"
	.align 1
	
gMetatileAttributes_PokeScapeOutdoors::
	.incbin "data/tilesets/primary/PokeScapeOutdoors/metatile_attributes.bin"
	.align 1
	
gMetatiles_Lumbridge::
	.incbin "data/tilesets/secondary/lumbridge/metatiles.bin"
	.align 1
	
gMetatileAttributes_Lumbridge::
	.incbin "data/tilesets/secondary/lumbridge/metatile_attributes.bin"
	
	.align 1
gMetatiles_PokeScapeIndoors::
	.incbin "data/tilesets/primary/PokeScapeIndoors/metatiles.bin"
	.align 1
	
gMetatileAttributes_PokeScapeIndoors::
	.incbin "data/tilesets/primary/PokeScapeIndoors/metatile_attributes.bin"
	.align 1
	
gMetatiles_Lumbridge_Swamp::
	.incbin "data/tilesets/secondary/lumbridge_swamp/metatiles.bin"
	.align 1
	
gMetatileAttributes_Lumbridge_Swamp::
	.incbin "data/tilesets/secondary/lumbridge_swamp/metatile_attributes.bin"
	.align 1
gMetatiles_Windmill::
	.incbin "data/tilesets/secondary/windmill/metatiles.bin"

	.align 1
gMetatileAttributes_Windmill::
	.incbin "data/tilesets/secondary/windmill/metatile_attributes.bin"
	.align 1
gMetatiles_Rimmington::
	.incbin "data/tilesets/secondary/rimmington/metatiles.bin"

	.align 1
gMetatileAttributes_Rimmington::
	.incbin "data/tilesets/secondary/rimmington/metatile_attributes.bin"
	.align 1
gMetatiles_Bank::
	.incbin "data/tilesets/secondary/bank/metatiles.bin"

	.align 1
gMetatileAttributes_Bank::
	.incbin "data/tilesets/secondary/bank/metatile_attributes.bin"
	.align 1
gMetatiles_Draynor::
	.incbin "data/tilesets/secondary/draynor/metatiles.bin"

	.align 1
gMetatileAttributes_Draynor::
	.incbin "data/tilesets/secondary/draynor/metatile_attributes.bin"
	.align 1
gMetatiles_Falador::
	.incbin "data/tilesets/secondary/falador/metatiles.bin"

	.align 1
gMetatileAttributes_Falador::
	.incbin "data/tilesets/secondary/falador/metatile_attributes.bin"
	.align 1
gMetatiles_Varrock::
	.incbin "data/tilesets/secondary/varrock/metatiles.bin"

	.align 1
gMetatileAttributes_Varrock::
	.incbin "data/tilesets/secondary/varrock/metatile_attributes.bin"
	.align 1
gMetatiles_AlKharid::
	.incbin "data/tilesets/secondary/alkharid/metatiles.bin"

	.align 1
gMetatileAttributes_AlKharid::
	.incbin "data/tilesets/secondary/alkharid/metatile_attributes.bin"
	.align 1
gMetatiles_IndoorTowns1::
	.incbin "data/tilesets/secondary/indoortowns1/metatiles.bin"

	.align 1
gMetatileAttributes_IndoorTowns1::
	.incbin "data/tilesets/secondary/indoortowns1/metatile_attributes.bin"
	.align 1
gMetatiles_PokeScape_Church::
	.incbin "data/tilesets/secondary/pokescape_church/metatiles.bin"

	.align 1
gMetatileAttributes_PokeScape_Church::
	.incbin "data/tilesets/secondary/pokescape_church/metatile_attributes.bin"
	.align 1
gMetatiles_PokeScape_Caves::
	.incbin "data/tilesets/secondary/pokescape_caves/metatiles.bin"

	.align 1
gMetatileAttributes_PokeScape_Caves::
	.incbin "data/tilesets/secondary/pokescape_caves/metatile_attributes.bin"
	.align 1
gMetatiles_Karamja::
	.incbin "data/tilesets/secondary/karamja/metatiles.bin"

	.align 1
gMetatileAttributes_Karamja::
	.incbin "data/tilesets/secondary/karamja/metatile_attributes.bin"
	.align 1
gMetatiles_Wizards_Tower::
	.incbin "data/tilesets/secondary/wizards_tower/metatiles.bin"

	.align 1
gMetatileAttributes_Wizards_Tower::
	.incbin "data/tilesets/secondary/wizards_tower/metatile_attributes.bin"
	.align 1
gMetatiles_DraynorManor::
	.incbin "data/tilesets/secondary/draynormanor/metatiles.bin"

	.align 1
gMetatileAttributes_DraynorManor::
	.incbin "data/tilesets/secondary/draynormanor/metatile_attributes.bin"
	.align 1
gMetatiles_QueenBlackDragon::
	.incbin "data/tilesets/secondary/queenblackdragon/metatiles.bin"

	.align 1
gMetatileAttributes_QueenBlackDragon::
	.incbin "data/tilesets/secondary/queenblackdragon/metatile_attributes.bin"
	.align 1
gMetatiles_Pub::
	.incbin "data/tilesets/secondary/pub/metatiles.bin"

	.align 1
gMetatileAttributes_Pub::
	.incbin "data/tilesets/secondary/pub/metatile_attributes.bin"
	.align 1
gMetatiles_Lumbridge_Swamp_Caves::
	.incbin "data/tilesets/secondary/lumbridge_swamp_caves/metatiles.bin"

	.align 1
gMetatileAttributes_Lumbridge_Swamp_Caves::
	.incbin "data/tilesets/secondary/lumbridge_swamp_caves/metatile_attributes.bin"
	.align 1
gMetatiles_Abyss::
	.incbin "data/tilesets/secondary/abyss/metatiles.bin"

	.align 1
gMetatileAttributes_Abyss::
	.incbin "data/tilesets/secondary/abyss/metatile_attributes.bin"
	.align 1
gMetatiles_GoblinVillage::
	.incbin "data/tilesets/secondary/goblinvillage/metatiles.bin"

	.align 1
gMetatileAttributes_GoblinVillage::
	.incbin "data/tilesets/secondary/goblinvillage/metatile_attributes.bin"
	.align 1
gMetatiles_Wilderness::
	.incbin "data/tilesets/secondary/wilderness/metatiles.bin"

	.align 1
gMetatileAttributes_Wilderness::
	.incbin "data/tilesets/secondary/wilderness/metatile_attributes.bin"
	.align 1
gMetatiles_Barbarian_Village::
	.incbin "data/tilesets/secondary/barbarian_village/metatiles.bin"

	.align 1
gMetatileAttributes_Barbarian_Village::
	.incbin "data/tilesets/secondary/barbarian_village/metatile_attributes.bin"
	.align 1
gMetatiles_PokeScape_Sewers::
	.incbin "data/tilesets/secondary/pokescape_sewers/metatiles.bin"

	.align 1
gMetatileAttributes_PokeScape_Sewers::
	.incbin "data/tilesets/secondary/pokescape_sewers/metatile_attributes.bin"
	.align 1
gMetatiles_Mazcab::
	.incbin "data/tilesets/secondary/mazcab/metatiles.bin"

	.align 1
gMetatileAttributes_Mazcab::
	.incbin "data/tilesets/secondary/mazcab/metatile_attributes.bin"
	.align 1
gMetatiles_Dungeoneering::
	.incbin "data/tilesets/secondary/dungeoneering/metatiles.bin"

	.align 1
gMetatileAttributes_Dungeoneering::
	.incbin "data/tilesets/secondary/dungeoneering/metatile_attributes.bin"
	.align 1
gMetatiles_PokeScape_HAM::
	.incbin "data/tilesets/secondary/pokescape_ham/metatiles.bin"

	.align 1
gMetatileAttributes_PokeScape_HAM::
	.incbin "data/tilesets/secondary/pokescape_ham/metatile_attributes.bin"
	.align 1
gMetatiles_Edgeville::
	.incbin "data/tilesets/secondary/edgeville/metatiles.bin"

	.align 1
gMetatileAttributes_Edgeville::
	.incbin "data/tilesets/secondary/edgeville/metatile_attributes.bin"
	.align 1
gMetatiles_IndoorTowns2::
	.incbin "data/tilesets/secondary/indoortowns2/metatiles.bin"

	.align 1
gMetatileAttributes_IndoorTowns2::
	.incbin "data/tilesets/secondary/indoortowns2/metatile_attributes.bin"
	.align 1
gMetatiles_Yanille::
	.incbin "data/tilesets/secondary/yanille/metatiles.bin"

	.align 1
gMetatileAttributes_Yanille::
	.incbin "data/tilesets/secondary/yanille/metatile_attributes.bin"

	.align 1
gMetatiles_Ice_Mountain::
	.incbin "data/tilesets/secondary/ice_mountain/metatiles.bin"

	.align 1
gMetatileAttributes_Ice_Mountain::
	.incbin "data/tilesets/secondary/ice_mountain/metatile_attributes.bin"